export const StrengthSlugs = [
  'carefulness',
  'compassion',
  'courage',
  'creativity',
  'curiosity',
  'enthusiasm',
  'fairness',
  'forgiveness',
  'gratitude',
  'grit',
  'honesty',
  'hope',
  'humour',
  'judgement',
  'kindness',
  'leadership',
  'love',
  'love-of-beauty',
  'love-of-learning',
  'modesty',
  'perseverance',
  'perspective',
  'self-regulation',
  'social-intelligence',
  'spirituality',
  'teamwork',
] as const;

export type StrengthSlug = (typeof StrengthSlugs)[number];

// For consistency, we reference strengths in the db by id. This is used to map
// the slug to the database ID
export const StrengthIDMap = {
  creativity: 'f89c4a9f-1dc4-4ccf-bd15-3c93e0087cc6',
  enthusiasm: 'f690128f-2b0b-486c-839e-7e160a395d31',
  hope: 'f151083b-171b-4123-884e-5bee988014d4',
  grit: 'eab87b14-2fcd-4b76-b1c1-3c87af21c076',
  spirituality: 'e9d30d66-4103-4a9a-92cf-aad476d11877',
  'love-of-learning': 'd9dadec3-6a9b-4554-b10c-10e1f388c808',
  'self-regulation': 'd7875ebe-2f73-4e1a-b77b-c40fa249f515',
  leadership: 'ce5f5f41-1a21-493d-93bb-d3f3b201e980',
  judgement: 'b621a4d2-97b0-4fca-8fef-70caf427a7c4',
  gratitude: 'b3173176-cf47-441a-96f0-e24b26736ea8',
  modesty: 'ae4ec648-a33a-4183-a155-4637f9c02b06',
  fairness: 'adc013fe-757f-47b6-97ab-5cbefa367973',
  carefulness: 'ac0ce5b7-1fb0-44f5-995a-296cbffb0abf',
  'social-intelligence': 'a6680492-fab9-4b31-a203-1dd31223739b',
  honesty: '9424de85-acb8-4fbf-baf2-ed66c101a920',
  courage: '889f2b4b-0730-4825-8962-48db602e647a',
  love: '79ac39bb-9abe-45da-a6c2-2cb2b990cbf9',
  'love-of-beauty': '604212b3-680b-4f0f-bc66-8f2fb9c71e28',
  perspective: '49bc1850-595d-4ab3-981d-911d94b85624',
  compassion: '3e44b716-de08-48e1-bbf5-e0def589ad3b',
  teamwork: '39302a21-24b1-4e97-a4e7-97a173150fe9',
  kindness: '2cde6616-2b78-4274-9562-e856c9dc0260',
  perseverance: '21dbe3a5-fd0d-40c9-b363-4b0c0f9eb1ff',
  humour: '157013a4-dd03-4930-a156-195155c1fcf3',
  curiosity: '04463d6a-ad3a-49da-98eb-1bc8dac0226e',
  forgiveness: '0418d77d-617c-44a6-98a5-97ad5efedce4',
};

export const StrengthSlugMap: Record<string, StrengthSlug> = {};

for (const [key, value] of Object.entries(StrengthIDMap)) {
  StrengthSlugMap[value] = key as StrengthSlug;
}

export type StrengthColors = {
  50: string;
  100: string;
  200: string;
  300: string;
  400: string;
  500: string;
};

export const StrengthColorMap = {
  carefulness: {
    50: '#F9FCF8',
    100: '#F2F8F1',
    200: '#ebf5ea',
    300: '#d7ebd6',
    400: '#A1D09F',
    500: '#468A42',
  },
  compassion: {
    50: '#F4F3F7',
    100: '#E9E7EF',
    200: '#DEDAE6',
    300: '#D0CBDC',
    400: '#B2AAC6',
    500: '#5E5379',
  },
  courage: {
    50: '#FFFBEB',
    100: '#FFF7D6',
    200: '#FFF3C2',
    300: '#FFE88A',
    400: '#FFDB47',
    500: '#F5C500',
  },
  creativity: {
    50: '#F1F7F9',
    100: '#E2EEF3',
    200: '#D4E6ED',
    300: '#4D97B5',
    400: '#3C7890',
    500: '#306073',
  },
  curiosity: {
    50: '#FDF2EC',
    100: '#FCE6D9',
    200: '#FAD9C7',
    300: '#F3A275',
    400: '#F08D56',
    500: '#ED7431',
  },
  enthusiasm: {
    50: '#FEF9F6',
    100: '#FDF2EC',
    200: '#FDEFE8',
    300: '#FCEAE0',
    400: '#F2A77D',
    500: '#EF8E58',
  },
  fairness: {
    50: '#F8FCF9',
    100: '#F1F8F2',
    200: '#EBF5EC',
    300: '#DDEEDF',
    400: '#A0CFA5',
    500: '#69B472',
  },
  forgiveness: {
    50: '#F0F9F8',
    100: '#B5E3DC',
    200: '#97D8CE',
    300: '#61C4B4',
    400: '#43B2A0',
    500: '#379585',
  },
  gratitude: {
    50: '#F1F8F2',
    100: '#D6EAD9',
    200: '#BBDDBF',
    300: '#ACD5B1',
    400: '#85C18C',
    500: '#6AB473',
  },
  grit: {
    50: '#FEF6F6',
    100: '#FEF2F1',
    200: '#FDEDED',
    300: '#FCE3E2',
    400: '#F5A6A3',
    500: '#F2827E',
  },
  honesty: {
    50: '#F0F9F8',
    100: '#E1F4F1',
    200: '#D3EEEA',
    300: '#B0E1D9',
    400: '#98D8CD',
    500: '#5CC1B1',
  },
  hope: {
    50: '#F0FAF8',
    100: '#B2E6DE',
    200: '#93DCD0',
    300: '#3AB5A1',
    400: '#329A89',
    500: '#287C6E',
  },
  humour: {
    50: '#F4F5F6',
    100: '#DDE0E4',
    200: '#AFB6C0',
    300: '#9DA5B2',
    400: '#818C9C',
    500: '#6C7789',
  },
  judgement: {
    50: '#FDEDED',
    100: '#F5A6A3',
    200: '#F1837F',
    300: '#EB524C',
    400: '#E83C35',
    500: '#DC2019',
  },
  kindness: {
    50: '#FFDBD9',
    100: '#FEC0BD',
    200: '#F5A6A3',
    300: '#EF7570',
    400: '#E72F27',
    500: '#AA1913',
  },
  leadership: {
    50: '#EFF4FA',
    100: '#D0DEF1',
    200: '#B1C8E7',
    300: '#8EAFDC',
    400: '#739CD4',
    500: '#5486CA',
  },
  love: {
    50: '#FDF2EC',
    100: '#F7C0A1',
    200: '#F4A77B',
    300: '#EF7F40',
    400: '#E25D13',
    500: '#BC4E10',
  },
  'love-of-beauty': {
    50: '#FEF2EC',
    100: '#FDECE3',
    200: '#FCE6D9',
    300: '#F9CCB3',
    400: '#F5A67B',
    500: '#EF732F',
  },
  'love-of-learning': {
    50: '#F1F7F9',
    100: '#E2EEF3',
    200: '#B7D5E1',
    300: '#9BC5D5',
    400: '#7EB4C9',
    500: '#61A3BD',
  },
  modesty: {
    50: '#FFFAEB',
    100: '#FFF7E1',
    200: '#FEF1CD',
    300: '#FEECB9',
    400: '#FDD972',
    500: '#FCC322',
  },
  perseverance: {
    50: '#EEFCFB',
    100: '#DDF1F0',
    200: '#D5ECEB',
    300: '#A5D7D5',
    400: '#6EBFBB',
    500: '#439894',
  },
  perspective: {
    50: '#FDEDEE',
    100: '#FBE4E6',
    200: '#FADBDE',
    300: '#F8C9CD',
    400: '#F3A5AB',
    500: '#EF818A',
  },
  'self-regulation': {
    50: '#FFF4D1',
    100: '#FFEFBE',
    200: '#FEE59A',
    300: '#FDD662',
    400: '#FCC112',
    500: '#BA8C02',
  },
  'social-intelligence': {
    50: '#F4F3F7',
    100: '#E9E7EF',
    200: '#C8C2D6',
    300: '#ABA2C1',
    400: '#9C91B6',
    500: '#8578A5',
  },
  spirituality: {
    50: '#F1F8F2',
    100: '#D6EBD9',
    200: '#BBDDBF',
    300: '#97CB9D',
    400: '#69B472',
    500: '#52A35B',
  },
  teamwork: {
    50: '#FFFAEB',
    100: '#FEE49A',
    200: '#FEDA72',
    300: '#FDC626',
    400: '#F3B502',
    500: '#CA9702',
  },
};

export const StrengthTranslationMap = {
  creativity: {
    'en-US': 'Creativity',
    'fi-FI': 'Luovuus',
    'sv-SE': 'Kreativitet',
  },
  enthusiasm: {
    'en-US': 'Enthusiasm',
    'fi-FI': 'Innostus',
    'sv-SE': 'Entusiasm',
  },
  hope: {
    'en-US': 'Hope',
    'fi-FI': 'Toiveikkuus',
    'sv-SE': 'Hopp',
  },
  grit: {
    'en-US': 'Grit',
    'fi-FI': 'Sisukkuus',
    'sv-SE': 'Sisu',
  },
  spirituality: {
    'en-US': 'Spirituality',
    'fi-FI': 'Hengellisyys',
    'sv-SE': 'Andlighet',
  },
  'love-of-learning': {
    'en-US': 'Love of Learning',
    'fi-FI': 'Oppimisen ilo',
    'sv-SE': 'Lärandets glädje',
  },
  'self-regulation': {
    'en-US': 'Self-regulation',
    'fi-FI': 'Itsesäätely',
    'sv-SE': 'Självkontroll',
  },
  leadership: {
    'en-US': 'Leadership',
    'fi-FI': 'Johtajuus',
    'sv-SE': 'Ledarskap',
  },
  judgement: {
    'en-US': 'Judgement',
    'fi-FI': 'Arviointikyky',
    'sv-SE': 'Omdöme',
  },
  gratitude: {
    'en-US': 'Gratitude',
    'fi-FI': 'Kiitollisuus',
    'sv-SE': 'Tacksamhet',
  },
  modesty: {
    'en-US': 'Modesty',
    'fi-FI': 'Vaatimat­tomuus',
    'sv-SE': 'Anspråks­löshet',
  },
  fairness: {
    'en-US': 'Fairness',
    'fi-FI': 'Reiluus',
    'sv-SE': 'Rättvisa',
  },
  carefulness: {
    'en-US': 'Carefulness',
    'fi-FI': 'Harkitse­vaisuus',
    'sv-SE': 'Efter­tänksamhet',
  },
  'social-intelligence': {
    'en-US': 'Social Intelligence',
    'fi-FI': 'Sosiaalinen älykkyys',
    'sv-SE': 'Social intelligens',
  },
  honesty: {
    'en-US': 'Honesty',
    'fi-FI': 'Rehellisyys',
    'sv-SE': 'Ärlighet',
  },
  courage: {
    'en-US': 'Courage',
    'fi-FI': 'Rohkeus',
    'sv-SE': 'Mod',
  },
  love: {
    'en-US': 'Love',
    'fi-FI': 'Rakkaus',
    'sv-SE': 'Kärlek',
  },
  'love-of-beauty': {
    'en-US': 'Love of Beauty',
    'fi-FI': 'Kauneuden arvostus',
    'sv-SE': 'Uppskatta det vackra',
  },
  perspective: {
    'en-US': 'Perspective',
    'fi-FI': 'Näkökulman­ottokyky',
    'sv-SE': 'Perspektiv­förmåga',
  },
  compassion: {
    'en-US': 'Compassion',
    'fi-FI': 'Myötätunto',
    'sv-SE': 'Empati',
  },
  teamwork: {
    'en-US': 'Teamwork',
    'fi-FI': 'Ryhmätyö­taidot',
    'sv-SE': 'Samarbets­förmåga',
  },
  kindness: {
    'en-US': 'Kindness',
    'fi-FI': 'Ystävällisyys',
    'sv-SE': 'Vänlighet',
  },
  perseverance: {
    'en-US': 'Perseverance',
    'fi-FI': 'Sinnikkyys',
    'sv-SE': 'Uthållighet',
  },
  humour: {
    'en-US': 'Humour',
    'fi-FI': 'Huumorintaju',
    'sv-SE': 'Humor',
  },
  curiosity: {
    'en-US': 'Curiosity',
    'fi-FI': 'Uteliaisuus',
    'sv-SE': 'Nyfikenhet',
  },
  forgiveness: {
    'en-US': 'Forgiveness',
    'fi-FI': 'Anteeksi­antavuus',
    'sv-SE': 'Förlåtelse',
  },
};

export const StrengthFinnishCasesMap = {
  creativity: {
    partitive: 'Luovuutta',
  },
  enthusiasm: {
    partitive: 'Innostusta',
  },
  hope: {
    partitive: 'Toiveikkuutta',
  },
  grit: {
    partitive: 'Sisukkuutta',
  },
  spirituality: {
    partitive: 'Hengellisyyttä',
  },
  'love-of-learning': {
    partitive: 'Oppimisen iloa',
  },
  'self-regulation': {
    partitive: 'Itsesäätelyä',
  },
  leadership: {
    partitive: 'Johtajuutta',
  },
  judgement: {
    partitive: 'Arviointikykyä',
  },
  gratitude: {
    partitive: 'Kiitollisuutta',
  },
  modesty: {
    partitive: 'Vaatimattomuutta',
  },
  fairness: {
    partitive: 'Reiluutta',
  },
  carefulness: {
    partitive: 'Harkitsevaisuutta',
  },
  'social-intelligence': {
    partitive: 'Sosiaalista älykkyyttä',
  },
  honesty: {
    partitive: 'Rehellisyyttä',
  },
  courage: {
    partitive: 'Rohkeutta',
  },
  love: {
    partitive: 'Rakkautta',
  },
  'love-of-beauty': {
    partitive: 'Kauneuden arvostusta',
  },
  perspective: {
    partitive: 'Näkökulmanottokykyä',
  },
  compassion: {
    partitive: 'Myötätuntoa',
  },
  teamwork: {
    partitive: 'Ryhmätyötaitoja',
  },
  kindness: {
    partitive: 'Ystävällisyyttä',
  },
  perseverance: {
    partitive: 'Sinnikkyyttä',
  },
  humour: {
    partitive: 'Huumorintajua',
  },
  curiosity: {
    partitive: 'Uteliaisuutta',
  },
  forgiveness: {
    partitive: 'Anteeksiantavuutta',
  },
};

export const StrengthFactsMap = {
  carefulness: {
    'en-US':
      'Carefulness shows in cautiousness while making decisions. A careful person considers matters from many angles and takes time to make her mind. Patience and immersing in details go hand-in-hand with carefulness.',
    'fi-FI':
      'Harkitsevaisuuteen liittyy huolellisuus ja varovaisuus päätöksissä. Harkitsevainen ihminen tarkastelee asioita monelta suunnalta ja antaa aikaa pohdinnoilleen. Maltti ja yksityiskohtiin perehtyminen kulkevat harkitsevuuden kumppaneina.',
    'sv-SE':
      'Eftertänksamhet betyder att man är omsorgsfull och försiktig i sina beslut. En eftertänksam person funderar noggrant på saker och ser dem ur flera vinklar. Tålamod och ett öga för detaljer går hand i hand med eftertänksamhet.',
  },
  compassion: {
    'en-US':
      "Compassion is the ability to recognize others' feelings. It means comforting another person in sorrow but also co-celebrating when things go fine. A compassionate person can put herself in the shoes of another person and understand diversity.",
    'fi-FI':
      'Myötätunto on kykyä havaita toisen tunnetiloja. Se on halua lohduttaa surussa mutta myös riemuita yhdessä ilon hetkellä. Myötätuntoinen ihminen osaa ajatella asioita toisten näkökulmasta ja ymmärtää erilaisuutta.',
    'sv-SE':
      'Medkänsla är förmågan att uppfatta en annans känslomässiga tillstånd. En person med medkänsla tröstar den som är ledsen och gläds tillsammans med den som är glad. En person med medkänsla kan tänka på saker ur andras perspektiv och förstår andras olikheter.',
  },
  courage: {
    'en-US':
      'Courage is the ability to act despite fear and insecurity. Courage opens up opportunities to experience and learn new things. Courage makes it easier to use other strengths.',
    'fi-FI':
      'Rohkeus on kykyä toimia pelosta ja epävarmuudesta huolimatta. Rohkeus avaa mahdollisuuksia kokea ja oppia uutta. Rohkeuden avulla muiden vahvuuksien käyttö helpottuu.',
    'sv-SE':
      'Mod är förmågan att handla trots att man är rädd eller osäker. Mod öppnar möjligheter till att uppleva och lära sig något nytt. Med mod blir det lättare att använda de andra styrkorna.',
  },
  creativity: {
    'en-US':
      'Creativity involves having the courage to experiment and do things in your own way, being rich in ideas and artistic expression. Creativity is reflected in everyday life as inventiveness and a desire to do things in your own way.',
    'fi-FI':
      'Luovuus on uskallusta kokeilla ja tehdä asioita omaperäisellä tavalla. Se on ideointia ja taiteellista ilmaisuvoimaa. Luovuus näkyy kekseliäisyytenä ja ongelmanratkaisukykynä monilla elämänalueilla.',
    'sv-SE':
      'Kreativitet är mod att experimentera och göra saker på ett sitt eget sätt, men också idérikedom och konstnärlig uttrycksförmåga. En kreativ person är uppfinningsrik och bra på att lösa problem i många områden i livet.',
  },
  curiosity: {
    'en-US':
      'Curiosity means willingness to seek and try, to see and learn a variety of things.Curiosity is natural in children leading them to explore their surroundings. A curious person asks a lot, finds out about many kind of matters and looks for new experiences.',
    'fi-FI':
      'Uteliaisuus on halua etsiä ja kokeilla uutta, nähdä ja oppia erilaisia asioita. Uteliaisuus on lapsissa luontaista ja johtaa tutkimiseen.Utelias ihminen kyselee paljon, ottaa asioista selvää ja hakee elämyksiä.',
    'sv-SE':
      'Nyfikenhet är lusten att söka och testa nytt, att se och lära sig olika saker. Nyfikenhet är en medfödd egenskap hos barn och leder till utforskning av världen. En nyfiken person frågar mycket, tar reda på saker och söker upplevelser.',
  },
  enthusiasm: {
    'en-US':
      'An enthusiastic person is energetic and works towards the desired goal. He/she accomplishes a lot and is generally happy with his life. He can infect enthusiasm with others.',
    'fi-FI':
      'Innostuneena ihminen on tarmokas ja toimii kohti haluamaansa päämäärää. Hän saa paljon aikaiseksi ja on yleensä tyytyväinen elämäänsä. Hän voi tartuttaa intoa toisiinkin.',
    'sv-SE':
      'En entusiastisk person är driftig och arbetar hårt för att uppnå det uppsatta målet. Hen får mycket gjort och är oftast nöjd med sitt liv. Hen kan också smitta andra med sin entusiasm.',
  },
  fairness: {
    'en-US':
      'A fair person treats everyone equal. Fairness means flexibility and justice. A fair person ignores unnecessary minor issues. She can help and forgive others.',
    'fi-FI':
      'Reilu henkilö kohtelee kaikkia tasapuolisesti. Reiluus on joustavuutta ja oikeudenmukaisuutta ja turhien pikkuseikkojen ohittamista. Reilu tyyppi auttaa muita ja osaa antaa anteeksi.',
    'sv-SE':
      'En rättvis person behandlar alla lika. Rättvisa handlar om att vara flexibel och opartisk och att kunna förbise onödiga småsaker. En rättvis typ hjälper andra och har förmågan att förlåta.',
  },
  forgiveness: {
    'en-US':
      'A person with the strength of forgiveness is ready to forget the wrong doings she has faced. She respects peaceful living and looks for a chance to reconciliation. She can also forgive to herself.',
    'fi-FI':
      'Anteksiantavava ihminen on valmis unohtamaan kokemansa vääryydet. Hän arvostaa rauhallista yhdessäoloa ja hakee tilaisuutta sovinnolle. Anteeksiantavuuteen kuuluu myös kyky antaa itselleen anteeks ja uusi mahdollisuus.',
    'sv-SE':
      'En förlåtande person har förmågan att glömma orättvisor. Hen uppskattar fridfull samvaro och söker sämja och samförstånd. Att kunna förlåta sig själv och ge sig själv en ny chans hör också till förmågan att förlåta.',
  },
  gratitude: {
    'en-US':
      'Gratitude bears the ability to admire small things and pay attention to the good. A grateful person often thinks how happy she is. She can feel comfortable in many places.',
    'fi-FI':
      'Kiitollisuuteen kuuluu kyky ihastella pieniä asioita ja huomion kiinnittäminen hyvään. Kiitollinen ihminen pysähtyy usein miettimään, miten onnekas hän on. Kiitollisen ihmisen on helppo viihtyä monessa paikassa.',
    'sv-SE':
      'Tacksamhet betyder att man ser det fina i små saker och uppmärksammar det goda. En tacksam person stannar ofta upp för att tänka på hur lycklig hen har. Den som är tacksam brukar trivas nästan överallt.',
  },
  grit: {
    'en-US':
      'Grit (or the Finnish Sisu) is characterized by endurance in the face of obstacles, striving to reach a goal that may be far away. A gritty person has integrity to pursuit the destinations she finds right. She increases gas when headwind gets stronger.',
    'fi-FI':
      'Sisukkuus on matkan jatkamista esteistä huolimatta, ponnistelua kohti loitontuvaakin määränpäätä. Sisukas ihminen toimii lahjomattomasti oikeina pitämiensä tavoitteiden eteen ja lsää kierroksia, kun vastatuuli yltyy.',
    'sv-SE':
      'Ihärdighet betyder att man fortsätter resan trots mödor och strävar efter målet trots att det kan verka avlägset. En ihärdig person är orubblig och bara eggas av motstånd.',
  },
  honesty: {
    'en-US':
      'Honesty means having a strong sense of justice and defending the truth. An honest person says how the things really are even though it might cause her troubles. It goes with honesty to admit being wrong sometimes.',
    'fi-FI':
      'Rehellisyyttä kuvaa voimakas oikeudentunto ja totuuden puolustaminen. Rehellinen ihminen kertoo asiat kuten ne ovat, vaikka hän itse joutuisi ongelmiin. Rehellisyyteen kuuluu myös kyky myöntää olevansa joskus väärässä.',
    'sv-SE':
      'Att vara ärlig innebär att man har en stark känsla för rättvisa och försvarar sanningen. En ärlig person berättar sanningen, även om hen själv skulle råka illa ut. Ärlighet betyder också förmågan att erkänna att man själv ibland har fel.',
  },
  hope: {
    'en-US':
      'Hope means having a positive attitude to life and seeing opportunities in the future. A hopeful person can spark optimism in other people helping them find light even in dark times. Having hope and seeing good go together.',
    'fi-FI':
      'Toiveikkuus tarkoittaa positiivista suhtautumista elämään ja mahdollisuuksien näkemistä tulevaisuudessa. Toiveikkuuden avulla voi valaa uskoa toisiin ihmisiin ja auttaa näkemään valoa myös synkkinä hetkinä. Toiveikas ihminen huomaa hyvää.',
    'sv-SE':
      'Hoppfullhet betyder att man har en positiv inställning till livet och ser möjligheter i framtiden. Hoppfullhet kan ingjuta hopp i andra människor och hjälper att se ljuset även i mörka stunder. En hoppfull person ser det goda.',
  },
  humour: {
    'en-US':
      'Humour means a tendency to bring playfulness and fun to everyday events. Humorous person sees often comical side of the matter and is able to lighten the mood.',
    'fi-FI':
      'Huumorintaju tarkoittaa taipumusta tuoda leikillisyyttä ja hassuttelua arjen tapahtumiin. Huumorintajuinen ihminen näkee asioissa usein koomisenkin puolen ja osaa keventää tunnelmaa.',
    'sv-SE':
      'Att ha ett sinne för humor betyder att man tillför lekfullhet och skoj i vardagen. En person med ett sinne för humor ser ofta det komiska i tillvaron och vet hur man lättar upp stämningen.',
  },
  judgement: {
    'en-US':
      'Judgement means being able to find solutions based on the heaviest evidence. A person with judgement sees the forest for the trees and she can tell right from wrong.She can be critical to her own actions as well.',
    'fi-FI':
      'Arviointikyky on päätösten tekemistä painavimpien seikkojen pohjalta. Arviointikykyinen henkilö näkee metsän puilta ja erottaa oikean väärästä. Hän osaa tarkastella kriittisesti myös omaa toimintaansa.',
    'sv-SE':
      'Bedömningsförmåga betyder att man kan fatta beslut utifrån viktig information. En person med bedömningsförmåga ser skogen för träden och kan skilja gott från ont. Hen kan också granska sig själv kritiskt.',
  },
  kindness: {
    'en-US':
      'Kindness reflects the will to act for the benefit of others. It is ability to see others in positive ways, speak nicely and help others. Kindness is the foundation of successful relationships.',
    'fi-FI':
      'Ystävällisyys kuvastaa halua toimia toisten hyväksi. Se on kykyä katsoa toisia myönteisessä valossa, puhua kauniisti ja auttaa. Ystävällisyys on onnistuneiden ihmissuhteiden lähtökohta.',
    'sv-SE':
      'Vänlighet betyder att man handlar för andras bästa. Det är förmågan att se andra i ett positivt ljus, att tala vackert och att hjälpa andra. Vänlighet är utgångspunkten i alla lyckade relationer.',
  },
  leadership: {
    'en-US':
      'Leadership means responsibility for the task and the group. A leader takes care of others and shares the work based on strengths in others. A leader makes decisions which affect the success of the whole team.',
    'fi-FI':
      'Johtajuuteen kuuluu vastuu tehtävästä ja ryhmästä. Johtaja huolehtii muista ja jakaa työt kunkin osaamiseen perustuen. Johtaja tekee päätöksiä, joista koko porukan menestyminen riippuu.',
    'sv-SE':
      'Ledarskap innebär att ta ansvar för uppgiften och gruppen. En ledare tar hand om de andra och fördelar arbetet enligt var och ens kompetens. Ledaren fattar besluten som hela gruppens framgång hänger på.',
  },
  love: {
    'en-US':
      'Love means deep, warm connection to other people, animals, nature or even a hobby. There are several types of love. A loving person expresses her positive feelings easily and often.',
    'fi-FI':
      'Rakkaudella tarkoitetaan syvää lämmintä suhtautumista toisiin ihmisiin, eläimiin, luontoon tai vaikkapa harrastukseen. Rakkaudessa on monia lajeja Rakkaudellinen ihminen ilmaisee positiivisia tunteitaan helposti ja usein.',
    'sv-SE':
      'Kärleksfullhet betyder att man har en djupt och varm inställning till andra människor, djur, naturen eller till och med en hobby. Det finns många olika typer av kärleksfullhet. En kärleksfull person ger uttryck för sina positiva känslor lätt och ofta.',
  },
  'love-of-beauty': {
    'en-US':
      'Love of beauty describes the ability to recognize excellence in many places. Soap bubbles, roar of thunder, or lyrics of a song can inspire a lover of beauty. Love of beauty entails the skill to respect capabilities that one does not find interesting herself.',
    'fi-FI':
      'Kauneuden arvostus on kykyä havaita upeutta monissa paikoissa. Saippuakuplat, ukkosen jylinä tai laulunsanat voivat sytyttää kauneuden arvostajan. Kauneuden arvostukseen kuuluu myös kyky kunnioittaa osaamista, joka itseä ei kiinnosta.',
    'sv-SE':
      'Att ha ett sinne för estetik betyder att man kan finna skönhet överallt. Såpbubblor, åskdunder eller orden i en låt kan få en person med sinne för estetik att fatta lågor. Den som uppskattar skönhet har också respekt för färdigheter som hen inte själv nödvändigtvis är intresserad av.',
  },
  'love-of-learning': {
    'en-US':
      'Love of learning is described by willingness to get knowledge and experience of something new. This strength inspires constant exploration and discovery. A person with love of learning does not necessarily ask what for the learning is but enjoys the learning itself.',
    'fi-FI':
      'Oppimisen iloa kuvaa halu saada tietoa ja kokea uutta. Tämä vahvuus inspiroi jatkuvaan tutkimiseen ja löytämiseen Oppimisestaan iloinen ihminen ei välttämättä kysy, mihin oppimaansa tarvitsee vaan iloitsee itse oppimisesta.',
    'sv-SE':
      'Lärlust är viljan att veta och uppleva nytt. Det är en styrka som inspirerar till utforskning och upptäckter. En person med lärlust frågar inte nödvändigtvis varför hen lär sig, utan blir glad av att bara lära sig något nytt.',
  },
  modesty: {
    'en-US':
      "Modesty shows in letting others shine and staying silent about one's own achievements. A modest person lets the facts speak for themselves. She underlines co-operation instead of highlighting her own share.",
    'fi-FI':
      'Vaatimattomuus näkyy taipumuksena antaa toisille tilaa ja vaieta omista saavutuksista. Vaatimaton ihminen antaa tekojen puhua puolestaan. Hän korostaa yhdessä tekemistä oman osuutensa asemesta.',
    'sv-SE':
      'Anspråkslöshet betyder att man ger plats åt andra och inte skryter med sina egna prestationer. En anspråkslös person låter sina handlingar tala för sig själva. För hen är det viktigare att göra saker tillsammans än att framhäva sin egen roll.',
  },
  perseverance: {
    'en-US':
      'Perseverance is determination to hold on to the task. It is to continue in face of a seemingly impossible challenge. It is ability to recover after adversities (= resilience).',
    'fi-FI':
      'Sinnikkyys on päättäväisyyttä saavuttaa pitkäkestoisia tavoitteita. Se on jatkamista mahdottomaltakin tuntuvan haasteen edessä. Se on toipumiskykyä hankaluuksien jälkeen ja itsensä ylittämistä.',
    'sv-SE':
      'Uthållighet betyder att man är beslutsam och strävar efter långsiktiga mål. Det betyder att man fortsätter trots svåra utmaningar och har förmågan att återhämta sig efteråt.',
  },
  perspective: {
    'en-US':
      'Perspective is the ability to perceive entities. It is judgment, wisdom, and often also knowledge and life experience. Perspective includes the ability to put oneself to another person’s shoes.',
    'fi-FI':
      'Näkökulmanottokyky on taitoa tarkastella asioita monelta kannalta. Se on arviointia, viisautta ja usein myös tietoa sekä elämänkokemusta. Näkökulmanottokykyinen ihminen osaa asettua toisen asemaan ja vaihtaa tarvittaessa mielipidettä.',
    'sv-SE':
      'Perspektivförmåga är förmågan att se saker ur många perspektiv. Det betyder bedömningsförmåga, visdom och ofta även kunskap och livserfarenhet. En person med perspektivförmåga kan sätta sig in i en annans situation och byta sin åsikt om det behövs.',
  },
  'self-regulation': {
    'en-US':
      "Self-regulation is the ability to consciously control one's own actions. It is power to regulate behavior and emotions to suit the situation. Related concepts are willpower, executive functions and self-discipline.",
    'fi-FI':
      'Itsesäätely on kykyä ohjata tietoisesti omaa toimintaa. Se on käyttäytymisen ja tunteiden säätelyä tilanteeseen sopivaksi. Itsesäätelyyn liittyy kyky torjua houkutuksia, pysyä annetussa tehtävässä ja saattaa asioita valmiiksi.',
    'sv-SE':
      'Självreglering betyder att medvetet kontrollera sina egna handlingar och känslor enligt situationen. Självreglering innebär också förmågan att motstå frestelser, hålla sig till den givna uppgiften och att få saker gjorda.',
  },
  'social-intelligence': {
    'en-US':
      "Social intelligence is the ability to understand one's own and others' feelings, thoughts, and behaviors. It is ability to work well with different people. Empathy, situational awareness and friendship are important.",
    'fi-FI':
      'Sosiaalinen älykkyys on kykyä ymmärtää toisten tunteita ja tulkita tilanteita hienovaraisesti. Se on taitoa tulla toimeen erilaisten ihmisen kanssa ja saada toiset viihtymään. Sosiaalista älykkyyttä on myös kyky suostutella ja kääntää toiset puolelleen.',
    'sv-SE':
      'Social intelligens handlar om att förstå andras känslor och att tolka sociala situationer. En socialt intelligent person kommer överens med olika människor och får andra att känna sig bekväma, men kan också övertyga andra och få dem på sin sida.',
  },
  spirituality: {
    'en-US':
      'Spirituality means believing in something bigger and having a sense of purpose in life. A spiritual person feels joy and comfort while holding a belief of belonging to a greater plan. Spirituality is often connected to hope.',
    'fi-FI':
      'Hengellisyys tarkoittaa uskoa korkeampaan ja kokemusta elämän tarkoituksellisuudesta. Hengellinen ihminen kokee riemua ja lohtua tuntiessaan olevansa osa suurempaa suunnitelmaa. Hengellisyys on usein yhteydessä toiveikkuuteen.',
    'sv-SE':
      'Andlighet betyder att man tror på en högre makt och upplever att det finns en mening med livet. En andlig person känner glädje och tröst av att vara en del av en större plan. Andlighet kopplas ofta till hoppfullhet.',
  },
  teamwork: {
    'en-US':
      'Teamwork skills are reflected in active participation in the group. It is encouragement, enthusiasm and being active. It is also to give room, share tasks and working for common goals.',
    'fi-FI':
      'Ryhmätyötaidoilla tarkoitetaan joustavaa osallistumista ryhmän toimintaan. Se on kannustamista, innostumista ja aktiivisuutta. Se on myös tilan antamista, töiden jakamista ja työskentelyä tavoitteiden eteen.',
    'sv-SE':
      'Samarbetsförmåga innebär att man deltar i en grupp på ett mångsidigt sätt. Det handlar om att uppmuntra, entusiasmera och att vara aktiv, men också om att ge utrymme, dela arbete och arbeta mot ett gemensamt mål.',
  },
};

export const StrengthExamplesMap = {
  carefulness: {
    'en-US': 'Being cautious and paying close attention',
    'fi-FI': 'Huolellisuutta ja varovaisuutta toimissa ',
    'sv-SE': 'Att vara försiktig och uppmärksam',
  },
  compassion: {
    'en-US': "Understanding someone who's having a hard time",
    'fi-FI': 'Myötäelämistä toisen surussa ja ilossa',
    'sv-SE': 'Att förstå någon som har det svårt',
  },
  courage: {
    'en-US': 'Being brave and strong even in a scary situation',
    'fi-FI': 'Urhoollisuutta haasteiden edessä',
    'sv-SE': 'Att vara modig och stark även i en skrämmande situation',
  },
  creativity: {
    'en-US': 'Coming up with new and interesting ideas',
    'fi-FI': 'Uskallusta kokeilla ja tehdä asioita omaperäisesti',
    'sv-SE': 'Att komma med nya och intressanta idéer',
  },
  curiosity: {
    'en-US': 'Having a desire to explore new things',
    'fi-FI': 'Halua etsiä ja kokeilla uutta, nähdä ja oppia',
    'sv-SE': 'Att ha en önskan att utforska nya saker',
  },
  enthusiasm: {
    'en-US': 'Feeling super excited about something',
    'fi-FI': 'Energisyyttä, avoimuutta ja uteliaisuutta eri tilanteissa',
    'sv-SE': 'Att känna sig mycket entusiastisk över något',
  },
  fairness: {
    'en-US': 'Treating everyone equally',
    'fi-FI': 'Kaikkien tasapuolista kohtelua',
    'sv-SE': 'Att behandla alla lika',
  },
  forgiveness: {
    'en-US': 'Giving a second chance and moving on without a grudge',
    'fi-FI': 'Valmiutta antaa uusi mahdollisuus ja etsiä sovintoa',
    'sv-SE': 'Att ge en andra chans och gå vidare utan agg',
  },
  gratitude: {
    'en-US': 'Feeling thankful and appreciative',
    'fi-FI': 'Huomion kiinnittämistä hyvään ja sen arvostamista mitä on',
    'sv-SE': 'Att känna sig tacksam och uppskattande',
  },
  grit: {
    'en-US': 'Having a strong determination to not give up',
    'fi-FI': 'Vahvaa periksiantamattomuutta ',
    'sv-SE': 'Att ha en stark beslutsamhet att inte ge upp',
  },
  honesty: {
    'en-US': 'Telling the truth and being sincere',
    'fi-FI': 'Totuuteen pyrkimistä ja avoimuutta',
    'sv-SE': 'Att tala sanning och vara uppriktig',
  },
  hope: {
    'en-US': 'Believing good things can happen',
    'fi-FI': 'Positiivista suhtautumista elämään ja tulevaisuuteen ',
    'sv-SE': 'Att tro att goda saker kan hända',
  },
  humour: {
    'en-US': 'Spreading joy and happiness',
    'fi-FI': 'Ilon ja leikillisyyden levittämistä ympäristöön',
    'sv-SE': 'Att sprida glädje och lycka',
  },
  judgement: {
    'en-US': "Thinking what's right or wrong before making a decision",
    'fi-FI': 'Vaihtoehtojen pohtimista ennen päätöksentekoa',
    'sv-SE': 'Att fundera på vad som är rätt eller fel innan ett beslut fattas',
  },
  kindness: {
    'en-US': 'Being nice and helpful to others',
    'fi-FI': 'Ystävällisyyttä ja auttavaisuutta toisia kohtaan',
    'sv-SE': 'Att vara trevlig och hjälpsam mot andra',
  },
  leadership: {
    'en-US': 'Helping a team work together to reach their goals',
    'fi-FI': 'Toisten johtamista tavoitteen suunnassa',
    'sv-SE': 'Att hjälpa ett team att arbeta tillsammans för att nå sina mål',
  },
  love: {
    'en-US': 'Caring deeply for someone or something',
    'fi-FI': 'Syvää kiintymystä ja välittämistä',
    'sv-SE': 'Att bry sig mycket om någon eller något',
  },
  'love-of-beauty': {
    'en-US': 'Finding joy in the wonderful and pleasing things around',
    'fi-FI': 'Kykyä havaita kauneutta ympärillään',
    'sv-SE':
      'Att finna glädje i de underbara och behagliga sakerna runt omkring',
  },
  'love-of-learning': {
    'en-US': 'Being excited about gaining new knowledge and skills',
    'fi-FI': 'Halua saada tietoa ja oppia uutta ',
    'sv-SE':
      'Att vara entusiastisk över att öka sina kunskaper och färdigheter',
  },
  modesty: {
    'en-US': 'Being humble and not showing off',
    'fi-FI': 'Vaikenemista omista saavutuksista ',
    'sv-SE': 'Att vara ödmjuk och inte skryta',
  },
  perseverance: {
    'en-US': 'Having a strong willpower that helps to keep going',
    'fi-FI': 'Päättäväisyyttä saavuttaa päämääriä',
    'sv-SE': 'Att ha en stark viljestyrka som hjälper en att fortsätta',
  },
  perspective: {
    'en-US': 'Seeing and understanding  in different ways',
    'fi-FI': 'Taitoa tarkastella asioita monelta kannalta',
    'sv-SE': 'Att se och förstå på olika sätt',
  },
  'self-regulation': {
    'en-US': 'Controlling your emotions and actions',
    'fi-FI': 'Kykyä ohjata tietoisesti omaa toimintaa',
    'sv-SE': 'Att ha kontroll över sina känslor och handlingar',
  },
  'social-intelligence': {
    'en-US': 'Understanding and getting along with others',
    'fi-FI': 'Kykyä ymmärtää tulla toimeen toisten kanssa',
    'sv-SE': 'Att förstå och komma överens med andra',
  },
  spirituality: {
    'en-US': 'Connecting with deeper meanings and beliefs',
    'fi-FI': 'Uskoa korkeampaan ja kokemusta elämän tarkoituksellisuudesta',
    'sv-SE': 'Att få kontakt med djupare innebörder och övertygelser',
  },
  teamwork: {
    'en-US': 'Working together with others towards a goal',
    'fi-FI': 'Osallistumista ryhmän toimintaan yhteisen tavoitteen suunnassa',
    'sv-SE': 'Sammarbeta mot et gemensamt mål',
  },
};

export const StrengthAdjectivesMap = {
  carefulness: {
    'en-US': 'gentle, careful, watchful',
    'fi-FI': 'tarkka, varovainen, järjestelmällinen',
    'sv-SE': 'varsam, försiktig, vaksam',
  },
  compassion: {
    'en-US': 'caring, kind, understanding',
    'fi-FI': 'huolehtiva, ystävällinen, ymmärtäväinen',
    'sv-SE': 'omtänksam, vänlig, förstående',
  },
  courage: {
    'en-US': 'brave, strong, fearless',
    'fi-FI': 'rohkea, urhea, uskaltava',
    'sv-SE': 'modig, stark, orädd',
  },
  creativity: {
    'en-US': 'imaginative, inventive, artistic',
    'fi-FI': 'idearikas, ilmaisuvoimainen, taiteellinen',
    'sv-SE': 'fantasifull, uppfinningsrik, konstnärlig',
  },
  curiosity: {
    'en-US': 'questioning, eager, exploring',
    'fi-FI': 'tutkiva, etsivä, avoin',
    'sv-SE': 'frågvis, ivrig, utforskande',
  },
  enthusiasm: {
    'en-US': 'excited, energetic, passionate',
    'fi-FI': 'energinen, tarmokas, intohimoinen',
    'sv-SE': 'upprymd, energisk, passionerad',
  },
  fairness: {
    'en-US': 'equal, just, honest',
    'fi-FI': 'tasapuolinen, oikeudenmukainen, rehellinen',
    'sv-SE': 'jämlik, rättvis, ärlig',
  },
  forgiveness: {
    'en-US': 'understanding, kind, letting go',
    'fi-FI': 'ymmärtäväinen, ystävällinen, sovinnollinen',
    'sv-SE': 'förstående, vänlig, försonlig',
  },
  gratitude: {
    'en-US': 'thankful, appreciative, happy',
    'fi-FI': 'kiitollinen, arvostava, tyytyväinen',
    'sv-SE': 'tacksam, uppskattande, glad',
  },
  grit: {
    'en-US': 'persistent, determined, strong',
    'fi-FI': 'määrätietoinen, sinnikäs, vahva',
    'sv-SE': 'ihärdig, beslutsam, stark',
  },
  honesty: {
    'en-US': 'truthful, sincere, straightforward',
    'fi-FI': 'totuudenmukainen, suora, avoin',
    'sv-SE': 'sanningsenlig, uppriktig, rättfram',
  },
  hope: {
    'en-US': 'positive, optimistic, looking forward',
    'fi-FI': 'optimistinen, myönteinen, eteenpäin katsova',
    'sv-SE': 'positiv, optimistisk, framåtblickande',
  },
  humour: {
    'en-US': 'funny, playful, lighthearted',
    'fi-FI': 'hauska, leikkisä, hyväntuulinen',
    'sv-SE': 'rolig, lekfull, lättsinnig',
  },
  judgement: {
    'en-US': 'deciding, choosing, thinking',
    'fi-FI': 'ajatteleva, valikoiva, kriittinen',
    'sv-SE': 'beslutande, väljande, funderande',
  },
  kindness: {
    'en-US': 'caring, friendly, helpful',
    'fi-FI': 'huolehtiva, ystävällinen, auttavainen',
    'sv-SE': 'omtänksam, vänlig, hjälpsam',
  },
  leadership: {
    'en-US': 'guiding, helping, leading',
    'fi-FI': 'ohjaava, auttavainen, määrätietoinen',
    'sv-SE': 'vägledande, hjälpande, ledande',
  },
  love: {
    'en-US': 'caring, warm, affectionate',
    'fi-FI': 'välittävä, lämmin, huolehtiva',
    'sv-SE': 'omtänksam, varm, kärleksfull',
  },
  'love-of-beauty': {
    'en-US': 'appreciation, admiration, fascination',
    'fi-FI': 'arvostava, ihaileva, kiinnostunut',
    'sv-SE': 'uppskattning, beundran, fascination',
  },
  'love-of-learning': {
    'en-US': 'excitement, curiosity, exploration',
    'fi-FI': 'innostunut, kiinnostunut, utelias',
    'sv-SE': 'spänning, nyfikenhet, utforskning',
  },
  modesty: {
    'en-US': 'humble, simple, unpretentious',
    'fi-FI': 'nöyrä, yksinkertainen, aito',
    'sv-SE': 'ödmjuk, enkel, anspråkslös',
  },
  perseverance: {
    'en-US': 'determination, persistent, resilience',
    'fi-FI': 'määrätietoinen, päättäväinen, palautumiskykyinen',
    'sv-SE': 'beslutsam, uthållig, motståndskraftig',
  },
  perspective: {
    'en-US': 'viewpoint, understanding, openminded',
    'fi-FI': 'pohdiskeleva, avarakatseinen, ymmärtäväinen',
    'sv-SE': 'synvinkel, förstående, öppensinnad',
  },
  'self-regulation': {
    'en-US': 'control, emotions, balance',
    'fi-FI': 'tasapainoinen, hallittu, sopeutuva',
    'sv-SE': 'kontroll, känslor, balans',
  },
  'social-intelligence': {
    'en-US': 'understanding, empathy, relationships',
    'fi-FI': 'ymmärtäväinen, huomaavainen, myötätuntoinen',
    'sv-SE': 'förståelse, empati, relationer',
  },
  spirituality: {
    'en-US': 'wonder, connection, meaning',
    'fi-FI': 'merkitystä etsivä, ihmettelevä, toiveikas',
    'sv-SE': 'förundran, samhörighet, mening',
  },
  teamwork: {
    'en-US': 'together, cooperation, collaboration',
    'fi-FI': 'osallistuva, yhteistyökykyinen, joustava',
    'sv-SE': 'tillsammans, samarbete, samverkan',
  },
};

export const statements = {
  'fi-FI': {
    carefulness: [
      'Keskittymällä tarkasti yksityiskohtiin',
      'Ajattelemalla eteenpäin virheiden estämiseksi',
      'Kiinnittämällä suurta huomiota yksityiskohtiin työskennellessäni',
      'Tarkistamalla kahdesti toimenpiteeni tarkkuuden varmistamiseksi',
      'Ottamalla varotoimenpiteitä virheiden välttämiseksi',
      'Keskittymällä tarkasti yksityiskohtiin',
      'Ajattelemalla eteenpäin virheiden estämiseksi',
      'Jatkuvasti pyrkimällä parantamaan työtäni',
      'Olemalla tietoinen mahdollisista riskeistä tai vaaroista',
      'Ennakoiden ja suunnitellen mahdollisia haasteita',
      'Olemalla ahkera työskennellessäni laadun varmistamiseksi',
      'Olemalla huolellinen viestinnässä väärinkäsitysten välttämiseksi',
    ],
    compassion: [
      'Osoittamalla empatiaa muita kohtaan',
      'Välittämällä syvästi avun tarpeessa olevista',
      'Toimimalla ystävällisesti ja empaattisesti',
      'Olemalla tarkkaavainen muiden tunteille',
      'Olemalla sydän täynnä myötätuntoa',
      'Olemalla kärsivällinen ja ymmärtäväinen muita kohtaan',
      'Olemalla tuomitsematon ja hyväksyvä muita kohtaan',
      'Tarjoamalla emotionaalista tukea ja lohtua tarvitseville',
      'Olemalla antelias ja antava muita kohtaan',
      'Ajamalla muiden hyvinvointia',
    ],
    courage: [
      'Uskaltamalla vastoinkäymisten edessä',
      'Olemalla peloton tavoitteiden saavuttamisessa',
      'Olemalla valmis ottamaan haasteita vastaan',
      'Olemalla itsevarma omista kyvyistä',
      'Puolustamalla itseään ja muita',
      'Kohtaamalla pelot päättäväisesti ja rohkeasti',
      'Ottamalla harkittuja riskejä menestyksen saavuttamiseksi',
      'Puolustamalla oikein olevaa, vaikka vastassa olisi vastarintaa',
      'Ajamalla muutosta ja edistystä, vaikka se olisi vaikeaa',
      'Olemalla valmis astumaan ulos mukavuusalueelta',
    ],
    creativity: [
      'Ideoimalla innovatiivisia ideoita',
      'Innostamalla mielikuvituksellisilla ratkaisuilla',
      'Kokeilemalla uusia lähestymistapoja',
      'Omaksuen epätavallisen ajattelun',
      'Luomalla taidetta, joka lumoaa',
      'Haastaen vallitsevat käytännöt luovuudella',
      'Löytämällä kauneutta odottamattomasta',
      'Rakentamalla ainutlaatuisia ja alkuperäisiä suunnitelmia',
      'Rikkomaan rajoja mielikuvituksellisella taidolla',
      'Kannustamalla muita tavoittelemaan luovuutta',
    ],
    curiosity: [
      'Aina etsimällä oppiakseen enemmän',
      'Olemalla kiinnostunut ja utelias mieli',
      'Olemalla avoin uusille ideoille ja kokemuksille',
      'Innostuneesti omaksuen tuntemattoman',
      'Jatkuvasti tutkimalla ympäröivää maailmaa',
      'Jatkuvasti kysymyksiä esittämällä saadakseen syvemmän ymmärryksen',
      'Uusien kokemusten ja tiedon tyydyttämiseksi etsimällä',
      'Olettamuksia haastaen ja vaihtoehtoisia näkemyksiä tutkien',
      'Olemalla avoin mieli ja vastaanottavainen uusille ideoille ja tiedolle',
    ],
    enthusiasm: [
      'Lähestymällä haasteita innostuneella päättäväisyydellä',
      'Innostavalla innolla muiden innostaminen',
      'Uusien ideoiden omaksuminen innostuneella uteliaisuudella',
      'Innostuneesti jakamalla tavoite',
      'Positiivisuuden levittäminen innostuneella energialla',
      'Lähestymällä haasteita positiivisella asenteella ja innostuksella',
      'Innostavalla energialla ja innostuksella muiden innostaminen',
      'Olemalla intohimoinen työssä ja elämässä',
      'Positiivisuuden ja optimismi levittäminen missä tahansa liikkuukin',
      'Olemalla positiivisen energian ja motivaation lähde muille',
    ],
    fairness: [
      'Oikeudenmukaisuuden ja tasa-arvon edistäminen kaikille',
      'Muiden kohtelu oikeudenmukaisesti ja tasapuolisesti',
      'Eri näkökulmien ymmärtämisen tavoittelu',
      'Diversiteetin ja inklusiivisuuden kunnioittaminen',
      'Muiden voimaannuttaminen oikeudenmukaisen kohtelun kautta',
      'Edistääkseen kaikkien yksilöiden tasapuolista kohtelua',
      'Haastaen ennakkoluuloja ja syrjintää kaikissa muodoissa',
      'Pyrkimällä luomaan tasa-arvoiset pelisäännöt kaikille',
      'Diversiteetin ja inklusiivisuuden edistäminen kaikissa ympäristöissä',
      'Seisoen syrjittyjen ryhmien oikeuksien puolesta',
      'Systeemisten epäoikeudenmukaisuuksien tunnustaminen ja käsittely',
      'Oikeudenmukaisuutta ja tasa-arvoa edistävien politiikkojen ja aloitteiden tukeminen',
      'Varmistamalla, että valinnat perustuvat taitoihin ja kykyihin ihmisten henkilökohtaisista mieltymyksistä riippumatta.',
      'Olemalla avoin vaihtoehtoisille näkökulmille ja mielipiteille',
      'Kohtelemalla kaikkia kunnioittavasti, riippumatta siitä, kuka he ovat tai mistä he tulevat.',
    ],
    forgiveness: [
      'Hyväksymällä muiden anteeksipyynnöt epäröimättä',
      'Antamalla menneille loukkauksille anteeksi arvokkaasti',
      'Antamalla toisille mahdollisuuden avoimin sydämin',
      'Liikkumalla eteenpäin myötätunnolla ja ymmärryksellä',
      'Hyväksymällä anteeksipyynnön kasvun polkuna',
      'Päästämällä irti kaunasta muita kohtaan',
      'Näkemällä virheet mahdollisuuksina oppia ja kasvaa',
      'Tunnustaen, että anteeksianto on valinta',
      'Tarjoamalla anteeksianto lahjana itselle ja muille',
      'Tunnustamalla toisten inhimillisyyden ja kyvyn muuttua',
    ],
    gratitude: [
      'Arvostamalla elämän pieniä asioita',
      'Kiittämällä jokaista tilaisuutta',
      'Ilmaisemalla kiitollisuutta toisia kohtaan',
      'Kehittämällä kiitollista mieltä joka päivä',
      'Näkemällä hyvää kaikissa tilanteissa',
      'Löytämällä iloa elämän yksinkertaisista asioista',
      'Tunnistamalla hyvän jokaisessa tilanteessa',
      'Olemalla kiitollinen elämän ihmisistä',
      'Kehittämällä positiivista ja kiitollista mieltä',
      'Ilmaisemalla arvostusta elämän siunauksista',
      'Olemalla kiitollinen saaduista mahdollisuuksista',
      'Näkemällä haasteet mahdollisuuksina oppia ja kasvaa',
      'Tunnustamalla kovan työn ja sitkeyden arvon',
      'Antamalla takaisin muille kiitollisuuden ilmauksena',
      'Harjoittamalla kiitollisuutta itsehoidon ja tietoisuuden muotona',
    ],
    grit: [
      'Sitkeydellä selviytyminen haasteista',
      'Haasteiden voittaminen sitkeydellä',
      'Jatkuvasti pyrkimällä eteenpäin vastoinkäymisistä huolimatta',
      'Ylläpitämällä keskittymistä ja määrätietoisuutta vastoinkäymisten edessä',
      'Sitkeästi tavoitteiden tavoittelu raivokkaalla tahdolla',
      'Haasteiden omaksuminen mahdollisuuksina kasvaa',
      'Kieltäytymällä antamasta periksi vastoinkäymisissä',
      'Puskemalla epämukavuusalueen läpi tavoitteiden saavuttamiseksi',
      'Ylläpitämällä keskittymistä ja määrätietoisuutta pitkien ajanjaksojen aikana',
      'Olemalla sinnikäs ja sitkeä menestyksen tavoittelussa',
    ],
    honesty: [
      'Puhumalla totuudenmukaisesti kaikissa tilanteissa',
      'Virheiden myöntämisellä ja vastuun ottamisella',
      'Olemalla avoin ja aito',
      'Kunnioittamalla rehellisyyden tärkeyttä',
      'Pyrkimällä integriteettiin kaikissa toimissa',
      'Olemalla rehellinen, vaikka se olisi vaikeaa',
      'Ottamalla vastuun teoistaan ja virheistään',
      'Olemalla rehellinen itselleen vahvuuksistaan ja heikkouksistaan',
      'Välttämällä valheita tai totuuden vääristelyä negatiivisten seurausten välttämiseksi',
      'Olemalla avoin ja suora kommunikoinnissa',
    ],
    hope: [
      'Toivon ylläpitämisellä vaikeissa tilanteissa',
      'Toivon etsimisellä pimeinä aikoina',
      'Toivon hoitamisella itsessään ja muissa',
      'Valitsemalla toivo epätoivon sijaan',
      'Innostamalla muita toivorikkailla sanoilla ja teoilla',
      'Uskomalla parempaan tulevaisuuteen',
      'Löytämällä inspiraatiota vastoinkäymisten keskellä',
      'Luottamalla kykyyn selättää haasteita',
      'Pitämällä kiinni optimismista vaikeina aikoina',
      'Innostamalla toivoa muissa sanoilla ja teoilla',
      'Jatkamalla tavoitteiden tavoittelua esteistä huolimatta',
      'Näkemällä takaiskut väliaikaisina ja kasvun mahdollisuuksina',
      'Kultivoimalla sinnikkyyttä ja sitkeyttä toivon kautta',
      'Löytämällä voimaa toivosta ja positiivisuudesta',
      'Uskomalla, että asiat lopulta järjestyvät parhaalla mahdollisella tavalla',
    ],
    humour: [
      'Olemalla nopeasti ajatteleva ja leikkisä',
      'Tuo hymy toisten kasvoille',
      'Löytämällä iloa naurusta ja hauskasta',
      'Ei ottamalla asioita liian vakavasti',
      'Keventämällä tunnelmaa ja helpottamalla jännitteitä',
      'Löytämällä haastavista tilanteista hauskan puolen',
      'Käyttämällä huumoria jännitteiden ja konfliktien purkamiseen',
      'Levittämällä iloa naurun ja leikkisyyden kautta',
      'Olemalla leikkisä ja kevytmielinen vuorovaikutuksessa muiden kanssa',
      'Saamalla toiset nauramaan älykkäillä ja nokkelilla huomauksilla',
      'Löytämällä huumoria jokapäiväisistä tilanteista',
      'Olemalla kykenevä nauramaan itselleen eikä ottamaan itseään liian vakavasti',
      'Käyttämällä huumoria selviytymismekanismina vaikeina aikoina',
      'Olemalla lähde huumorille ja ilolle muille',
      'Tekemällä maailmasta kirkkaamman huumorin ja leikkisyyden kautta',
    ],
    judgement: [
      'Olemalla järkevä ja oikeudenmukainen päätöksissä perustuen todisteisiin ja järkeen',
      'Arvioimalla tilanteet huolellisesti ennen päätöksen tekemistä',
      'Punnitsemalla hyvät ja huonot puolet ennen valinnan tekemistä',
      'Harkitsemalla erilaisia näkökulmia ennen mielipiteen muodostamista',
      'Pystymällä tekemään vaikeita päätöksiä tarvittaessa',
      'Ottamalla vastuun teoistaan ja päätöksistään',
      'Pystymällä näkemään kokonaisuus samalla kun kiinnitetään huomiota yksityiskohtiin',
      'Käyttämällä hyvää harkintakykyä monimutkaisten tilanteiden navigoimiseen',
      'Tunnistamalla omat ennakkoluulot ja olemaan avoin uudelle tiedolle',
      'Tasapainottamalla järkeä ja intuitiota viisaiden päätösten tekemiseksi',
    ],
    kindness: [
      'Olemalla mukava muita ihmisiä kohtaan',
      'Auttamalla muita tarpeen tullen',
      'Olemalla ystävällinen ja ymmärtäväinen muita kohtaan',
      'Aktiivisesti kuuntelemalla ja ymmärtämällä muita',
      'Olemalla huomaavainen ja ajattelevainen muiden tunteista',
      'Olemalla läsnä toiselle heidän tarvitessaan',
      'Tarjoamalla ystävällinen sana tai ele, joka piristää jonkun päivää',
      'Auttamalla jotakuta, vaikka se ei olisi helppoa tai kätevää',
      'Olemalla ystävällinen jollekin, joka on vahingoittanut sinua',
      'Kohtelemalla kaikkia kunnioituksella, riippumatta heidän taustastaan tai uskomuksistaan',
    ],
    leadership: [
      'Innostamalla ja motivoimalla muita kohti menestystä',
      'Johtamalla esimerkillä integriteetillä ja tarkoituksella',
      'Kommunikoimalla tehokkaasti ohjatakseen ja johtaakseen',
      'Valtuuttamalla ja delegoimalla luottamuksella ja kunnioituksella',
      'Adaptoitumalla muutokseen ja ottamalla riskejä kasvun vuoksi',
      'Asettamalla selkeän vision ja suunnan tiimille',
      'Tarjoamalla ohjausta ja tukea auttaakseen muita menestymään',
      'Luo positiivinen ja inklusiivinen tiimikulttuuri',
      'Kannustaen luovuuteen ja innovaatioihin tiimin jäsenten keskuudessa',
      'Tunnistamalla ja hyödyntämällä tiimin jäsenten ainutlaatuisia vahvuuksia',
    ],
    love: [
      'Osoittamalla hellyyttä muita kohtaan',
      'Tarjoamalla emotionaalista tukea ja hoivaa',
      'Panemalla toisten tarpeet omien tarpeiden edelle',
      'Osoittamalla rakkautta sanojen ja tekojen kautta',
      'Säteilemällä lämpöä ja ystävällisyyttä muita kohtaan',
      'Arvostaen suhteita elämässä',
      'Osoittamalla rakkautta ystävällisin teoin',
      'Olemalla lähde tukea ja lohtua rakkaille',
      'Tekemällä aikaa rakkaille, vaikka olisi kiireinen aikataulu',
      'Tunnistamalla rakkauden tärkeyden elämässä',
      'Osoittamalla hellyyttä ja rakkautta niitä kohtaan, jotka ovat lähellä sydäntäsi',
      'Tekemällä uhrauksia niiden puolesta, joita rakastat',
      'Olemalla uskollinen ja sitoutunut niille, joita pidät rakkaana',
      'Juhlimalla rakkaiden saavutuksia ja menestyksiä',
      'Antamalla anteeksi niille, joita rakastat avoimin sydämin',
    ],
    'love-of-beauty': [
      'Ihailemalla kauniita asioita ja paikkoja',
      'Luomalla taidetta, joka inspiroi ja lumoaa',
      'Arvostaen yksinkertaisuuden eleganssia',
      'Löytämällä iloa elämän esteettisyydestä',
      'Näkemällä kauneutta yksityiskohdissa',
      'Löytämällä iloa muodin esteettisyydestä',
      'Arvostaen arkkitehtuurin ja suunnittelun kauneutta',
      'Ihailemalla luonnon kauneutta',
      'Luomalla kauniita ja toimivia tiloja',
      'Näkemällä kauneutta värien ja muotojen harmoniassa',
    ],
    'love-of-learning': [
      'Innoissaan etsimällä uutta tietoa',
      'Jatkuvasti oppimalla ja kasvamalla',
      'Ottamalla vastaan mahdollisuuksia koulutukseen',
      'Innokkaasti tavoitellen henkistä kasvua',
      'Sitä määrätietoisesti laajentamalla ymmärrystä',
      'Jatkuvasti etsimällä uusia haasteita ja mahdollisuuksia kasvuun',
      'Epäonnistumisen ja virheiden omaksuminen oppimismahdollisuuksina',
      'Innolla tavoitellen koulutusta ja henkilökohtaista kehitystä',
      'Jatkuvasti etsien uusia näkökulmia ja ideoita',
      'Kannustaenmuita tavoittelemaan omaa rakkauttaan oppimiseen',
    ],
    modesty: [
      'Osoittamalla arvostusta muiden panoksille',
      'Välttämällä huomionhakuisuutta',
      'Nöyrtyen saavutustensa edessä',
      'Mieltymällä pysymään taka-alalla',
      'Osoittamalla arvostusta toisten työlle',
      'Tunnistaen muiden panokset',
      'Mieltymällä työskentelemään taustalla',
      'Välttämällä itsekehua',
      'Antamalla tunnustusta toisten saavutuksille',
      'Keskittyen tiimin menestykseen henkilökohtaisen tunnustuksen sijaan',
    ],
    perseverance: [
      'Ei koskaan luovuttamalla',
      'Pysymällä keskittyneenä ja päättäväisenä haasteiden voittamiseksi',
      'Olemalla kestävä ja sinnikäs',
      'Pyrkiessä menestykseen haasteista huolimatta',
      'Jatkamalla eteenpäin vaikeuksista huolimatta',
      'Jatkamalla tavoitteen työstämistä, vaikka edistyminen olisi hidasta',
      'Kieltäytymällä luopumasta tehtävästä, kuinka vaikealta se sitten tuntuisikaan',
      'Voittamalla haasteet ja vastoinkäymiset kestävyydellä ja päättäväisyydellä',
      'Olemalla valmis tekemään ylimääräistä työtä menestyksen saavuttamiseksi',
      'Pitämällä fokuksen ja päättäväisyyden yllä häiriötekijöistä tai esteistä huolimatta',
    ],
    perspective: [
      'Etsimällä useita näkökulmia ennen päätöksentekoa',
      'Katsomalla tilanteita eri näkökulmista',
      'Tunnistamalla suuret linjat',
      'Ymmärtämällä erilaisia näkökulmia',
      'Haastamalla oletuksia kriittisellä ajattelulla',
      'Tunnistamalla oman tiedon ja ymmärryksen rajat',
      'Harkitsemalla päätösten ja toimien pitkäaikaisia vaikutuksia',
      'Ymmärtämällä kaiken olevan yhteydessä toisiinsa',
      'Tunnustamalla ja kunnioittamalla ihmisten monimuotoisuutta',
      'Lähestymällä tilanteita avoimin mielin ja halukkuudella oppia',
      'Tunnistamalla omat uskomukset ja oletukset',
      'Olemalla halukas haastamaan omat uskomukset ja oletukset',
      'Etsimällä monipuolisia näkökulmia ja kokemuksia laajentaakseen ymmärrystään',
      'Jatkuvasti laajentamalla omaa tietämystä ja maailmankuvaa oppimisen ja tutkimuksen kautta',
      'Sosiaalisten ja globaalien ongelmien monimutkaisuuden tunnistamalla ja olemalla halukas käsittelemään niitä',
    ],
    'self-regulation': [
      'Hallitsemalla tunteita',
      'Pysymällä keskittyneenä',
      'Viivyttämällä lyhyen aikavälin palkintoja',
      'Hallitsemalla stressiä ja ahdistusta',
      'Osoittamalla itsekontrollia',
      'Hallitsemalla impulsseja',
      'Pitämällä emotionaalinen tasapaino',
      'Olemalla tietoinen ja läsnä hetkessä',
      'Harjoittamalla itsensä hoitoa tunteiden hallitsemiseksi',
      'Kehittämällä selviytymismenetelmiä vaikeiden tilanteiden hallitsemiseksi',
      'Tekemällä valintoja fyysisen ja henkisen hyvinvoinnin edistämiseksi',
      'Asettamalla rajat ja hallitsemalla aikaa tehokkaasti',
      'Ottamalla vastuuta teoista ja päätöksistä',
      'Jatkuvasti oppimalla ja harjoittamalla itseparannusta',
      'Omaksuen muutoksen ja sopeutuen uusiin tilanteisiin',
    ],
    'social-intelligence': [
      'Osoittamalla herkkyyttä toisten tunteille',
      'Navigoimalla monimutkaisissa sosiaalisissa tilanteissa helposti',
      'Lukeutumalla rivien välistä keskusteluissa',
      'Rakentamalla vahvoja suhteita tehokkaan kommunikaation kautta',
      'Tunnistamalla ja reagoimalla asianmukaisesti sosiaalisiin vihjeisiin',
      'Osoittamalla empatiaa ja ymmärrystä toisten näkökulmista ja kokemuksista',
      'Olemalla tietoinen ja sopeutuva sosiaalisiin normeihin ja odotuksiin erilaisissa ympäristöissä',
      'Navigoimalla monimutkaisia sosiaalisia dynamiikoita taidokkaasti ja diplomaattisesti',
      'Kehittämällä positiivisia suhteita muiden kanssa tehokkaan viestinnän ja aktiivisen kuuntelun avulla',
      'Ratkaisemalla konflikteja ja väärinkäsityksiä rakentavalla ja kunnioittavalla tavalla',
    ],
    spirituality: [
      'Yhteydessä johonkin itseä suurempaan',
      'Etsimällä sisäistä rauhaa meditaation kautta',
      'Omaksuen henkisiä harjoituksia kasvun tueksi',
      'Ravitsemalla syvää merkitystä tuntevaa elämäntarkoitusta',
      'Löytämällä merkitystä elämän mysteereistä',
      'Omaksuen kiitollisuuden hengellisenä harjoituksena',
      'Elämällä omien arvojen ja uskomusten mukaisesti',
      'Yhteydessä luontoon henkisen uudistumisen lähteenä',
      'Tutkimalla erilaisia henkisiä perinteitä ja uskomuksia',
      'Integroimalla henkisiä harjoituksia päivittäiseen elämään merkityksen ja tarkoituksen löytämiseksi',
    ],
    teamwork: [
      'Tehokkaalla yhteistyöllä muiden kanssa',
      'Arvostamalla ja kunnioittamalla tiimin jäseniä',
      'Tukemalla aktiivisesti tiimin tavoitteita',
      'Jakamalla tietoa ja resursseja avoimesti ja halukkaasti',
      'Rakentamalla positiivisia suhteita tiimin jäsenten kanssa',
      'Olemalla valmis kompromisseihin ja yhteisten tavoitteiden saavuttamiseen',
      'Kommunikoimalla avoimesti ja rehellisesti tiimin jäsenten kanssa',
      'Edistämällä positiivista tiimidynamiikkaa',
      'Ottamalla vastuuta omasta roolistaan tiimin menestyksessä',
      'Osoittamalla joustavuutta ja sopeutumiskykyä muuttuvissa olosuhteissa',
      'Kunnioittamalla tiimin jäsenten mielipiteitä ja ideoita',
      'Olemalla valmis ottamaan erilaisia rooleja ja vastuita tarpeen mukaan',
      'Juhallemalla ja tunnustamalla tiimin jäsenten panokset ja onnistumiset',
      'Antamalla rakentavaa ja tukevaa palautetta tiimin jäsenille',
      'Osoittamalla sitoutumista tiimin tavoitteisiin ja menestykseen',
    ],
  },
  'sv-SE': {
    carefulness: [
      'Genom att vidta försiktighetsåtgärder för att undvika misstag',
      'Genom att ägna stor uppmärksamhet åt detaljer',
      'Genom att tänka framåt för att förhindra fel',
      'Genom att ägna stor uppmärksamhet åt detaljer när man arbetar',
      'Genom att dubbelkolla mina handlingar för korrekthet',
      'Genom att vidta försiktighetsåtgärder för att undvika misstag',
      'Genom att ägna stor uppmärksamhet åt detaljer',
      'Genom att tänka framåt för att förhindra fel',
      'Genom att ständigt sträva efter att förbättra mitt arbete',
      'Genom att vara medveten om potentiella risker eller faror',
      'Genom att förutse och planera för potentiella utmaningar',
      'Genom att vara noggrann när man arbetar för att säkerställa kvalitet',
      'Genom att vara försiktig när man kommunicerar för att undvika missförstånd',
    ],
    compassion: [
      'Genom att visa empati mot andra',
      'Genom att bry sig djupt om dem som behöver det',
      'Genom att agera med vänlighet och empati',
      'Genom att vara uppmärksam på andras känslor',
      'Genom att ha ett hjärta fullt av medkänsla',
      'Genom att vara tålmodig och förstående mot andra',
      'Genom att vara icke-dömande och accepterande av andra',
      'Genom att erbjuda känslomässigt stöd och tröst till dem som behöver det',
      'Genom att vara generös och givande mot andra',
      'Genom att förespråka för andras välbefinnande',
    ],
    courage: [
      'Genom att våga i motgångar',
      'Genom att vara orädd i jakten på mål',
      'Genom att vara villig att ta sig an utmaningar',
      'Genom att vara säker på sina förmågor',
      'Genom att stå upp för sig själva och andra',
      'Genom att möta rädslor direkt med tapperhet',
      'Genom att ta kalkylerade risker för att uppnå framgång',
      'Genom att stå upp för det som är rätt, även inför motstånd',
      'Genom att förespråka förändring och framsteg, även när det är svårt',
      'Genom att vara beredd att kliva utanför komfortzonen',
    ],
    creativity: [
      'Genom att brainstorma innovativa idéer',
      'Genom att inspirera med fantasifulla lösningar',
      'Genom att experimentera med nya tillvägagångssätt',
      'Genom att omfamna okonventionellt tänkande',
      'Genom att skapa konst som fångar',
      'Genom att utmana status quo med kreativitet',
      'Genom att finna skönhet i det oväntade',
      'Genom att utforma unika och originella designer',
      'Genom att flytta gränser med fantasifull flärd',
      'Genom att uppmuntra andra att sträva efter kreativitet',
    ],
    curiosity: [
      'Genom att alltid söka lära sig mer',
      'Genom att vara intresserad och ha en nyfiken inställning',
      'Genom att vara öppen för nya idéer och upplevelser',
      'Genom att omfamna det okända med entusiasm',
      'Genom att ständigt utforska världen runt omkring',
      'Genom att ständigt ställa frågor för att få en djupare förståelse',
      'Genom att söka efter nya upplevelser och kunskaper för att tillfredsställa nyfikenheten',
      'Genom att ifrågasätta antaganden och utforska alternativa perspektiv',
      'Genom att kontinuerligt utvidga sina vyer genom lärande och utforskning',
      'Genom att vara öppensinnad och mottaglig för nya idéer och information',
    ],
    enthusiasm: [
      'Genom att närma sig utmaningar med entusiastisk beslutsamhet',
      'Genom att inspirera andra med smittsam entusiasm',
      'Genom att omfamna nya idéer med entusiastisk nyfikenhet',
      'Genom att dela entusiasm för ett gemensamt mål',
      'Genom att sprida positivitet genom entusiastisk energi',
      'Genom att närma sig utmaningar med en positiv attityd och entusiasm',
      'Genom att inspirera andra med smittsam entusiasm och energi',
      'Genom att vara passionerad för arbete och liv',
      'Genom att sprida positivitet och optimism vart de än går',
      'Genom att vara en källa till positiv energi och motivation för andra',
    ],
    fairness: [
      'Genom att främja rättvisa och jämlikhet för alla',
      'Genom att behandla andra med rättvisa och jämlikhet',
      'Genom att söka förstå olika synpunkter',
      'Genom att respektera mångfald och inkludering',
      'Genom att stärka andra genom rättvis behandling',
      'Genom att verka för likabehandling av alla individer',
      'Genom att utmana fördomar och diskriminering i alla former',
      'Genom att sträva efter att skapa en jämn spelplan för alla',
      'Genom att främja mångfald och inkludering i alla miljöer',
      'Genom att stå upp för marginaliserade gruppers rättigheter',
      'Genom att erkänna och ta itu med systematiska ojämlikheter',
      'Genom att stödja policys och initiativ som främjar rättvisa och jämlikhet',
      'Genom att se till att val görs baserat på färdigheter och förmågor, inte personliga sympatier eller antipatier.',
      'Genom att vara öppensinnad inför alternativa perspektiv och åsikter',
      'Genom att behandla alla med respekt, oavsett vem de är eller var de kommer från.',
    ],
    forgiveness: [
      'Genom att acceptera andras ursäkter utan tvekan',
      'Genom att släppa taget om tidigare oförrätter med värdighet',
      'Genom att ge andra chanser med ett öppet hjärta',
      'Genom att gå vidare med medkänsla och förståelse',
      'Genom att omfamna förlåtelse som en väg till tillväxt',
      'Genom att släppa taget om agg mot andra',
      'Genom att se misstag som möjligheter att lära och växa',
      'Genom att erkänna att förlåtelse är ett val',
      'Genom att erbjuda förlåtelse som en gåva till sig själv och andra',
      'Genom att erkänna människans humanitet och förmåga till förändring',
    ],
    gratitude: [
      'Genom att uppskatta de små sakerna i livet',
      'Genom att tacka för varje möjlighet',
      'Genom att uttrycka tacksamhet gentemot andra',
      'Genom att odla en tacksam inställning varje dag',
      'Genom att se det goda i alla situationer',
      'Genom att finna glädje i livets enkla ting',
      'Genom att känna igen det goda i varje situation',
      'Genom att vara tacksam för människorna i sitt liv',
      'Genom att utveckla en positiv och tacksam inställning',
      'Genom att uttrycka uppskattning för livets välsignelser',
      'Genom att vara tacksam för givna möjligheter',
      'Genom att se utmaningar som möjligheter att lära sig och växa',
      'Genom att erkänna värdet av hårt arbete och uthållighet',
      'Genom att ge tillbaka till andra som ett uttryck för tacksamhet',
      'Genom att praktisera tacksamhet som en form av självomsorg och medvetenhet',
    ],
    grit: [
      'Genom att uthålligt ta sig igenom utmaningar med beslutsamhet',
      'Genom att övervinna utmaningar med beslutsamhet.',
      'Genom att kontinuerligt sträva efter framsteg trots motgångar',
      'Genom att bibehålla fokus och beslutsamhet inför motgångar',
      'Genom att ihärdigt förfölja mål med oförtröttlig styrka',
      'Genom att omfamna utmaningar som tillväxtmöjligheter',
      'Genom att vägra ge upp inför motgångar',
      'Genom att kämpa igenom obehag för att uppnå mål',
      'Genom att bibehålla fokus och beslutsamhet under långa tidsperioder',
      'Genom att vara motståndskraftig och uthållig i strävan efter framgång',
    ],
    honesty: [
      'Genom att tala sanningsenligt i alla situationer',
      'Genom att erkänna misstag och ta ansvar',
      'Genom att vara öppen och äkta',
      'Genom att respektera ärlighetens betydelse',
      'Genom att sträva efter integritet i alla handlingar',
      'Genom att vara sanningsenlig även när det är svårt',
      'Genom att ta ansvar för sina handlingar och misstag',
      'Genom att vara ärlig med sig själv om sina styrkor och svagheter',
      'Genom att avstå från att ljuga eller böja sanningen för att undvika negativa konsekvenser',
      'Genom att vara öppen och rakt på sak i kommunikationen',
    ],
    hope: [
      'Genom att bibehålla hoppet i svåra situationer',
      'Genom att söka hopp i mörka tider',
      'Genom att odla hopp hos sig själv och andra',
      'Genom att välja hopp framför förtvivlan',
      'Genom att inspirera andra med hoppfulla ord och handlingar',
      'Genom att tro på en bättre framtid',
      'Genom att finna inspiration inför motgångar',
      'Genom att lita på sin egen förmåga att övervinna utmaningar',
      'Genom att hålla fast vid optimism i svåra tider',
      'Genom att inspirera hopp hos andra genom ord och handlingar',
      'Genom att fortsätta förfölja mål trots hinder',
      'Genom att se motgångar som temporära och möjligheter till tillväxt',
      'Genom att odla motståndskraft och uthållighet genom hopp',
      'Genom att finna styrka i hopp och positivitet',
      'Genom att tro att saker och ting till slut kommer att ordna sig för det bästa',
    ],
    humour: [
      'Genom att vara snabbtänkt och lekfull',
      'Genom att få andra att le',
      'Genom att finna glädje i skratt och roliga stunder',
      'Genom att inte ta saker för allvarligt',
      'Genom att lätta upp stämningen och minska spänningar',
      'Genom att hitta den roliga sidan av svåra situationer',
      'Genom att använda humor för att minska spänningar och konflikter',
      'Genom att sprida glädje genom skratt och lekfullhet',
      'Genom att vara lekfull och lättsam i interaktioner med andra',
      'Genom att få andra att skratta med kvicka och fyndiga kommentarer',
      'Genom att hitta humor i vardagssituationer',
      'Genom att kunna skratta åt sig själv och inte ta sig själv för allvarligt',
      'Genom att använda humor som en copingmekanism i svåra tider',
      'Genom att vara en källa till humor och glädje för andra',
      'Genom att göra världen ljusare genom humor och lekfullhet',
    ],
    judgement: [
      'Genom att fatta sunda och rättvisa beslut baserade på förnuft och bevis',
      'Genom att noggrant utvärdera situationer innan man fattar ett beslut',
      'Genom att väga för- och nackdelar innan man gör ett val',
      'Genom att överväga olika perspektiv innan man bildar sig en åsikt',
      'Genom att kunna fatta svåra beslut när det behövs',
      'Genom att ta ansvar för sina handlingar och beslut',
      'Genom att kunna se helheten samtidigt som man ägnar uppmärksamhet åt detaljer',
      'Genom att använda gott omdöme för att navigera genom komplexa situationer',
      'Genom att känna igen sina egna fördomar och vara öppen för ny information',
      'Genom att balansera förnuft och intuition för att fatta kloka beslut',
    ],
    kindness: [
      'Genom att vara trevlig mot andra människor',
      'Genom att hjälpa andra i nöd',
      'Genom att vara snäll och förstående gentemot andra',
      'Genom att aktivt lyssna och förstå andra',
      'Genom att vara hänsynsfull och omtänksam inför andras känslor',
      'Genom att finnas där för någon i deras stund av behov',
      'Genom att erbjuda ett vänligt ord eller en gest för att lysa upp någons dag',
      'Genom att hjälpa någon även när det inte är enkelt eller bekvämt.',
      'Genom att vara snäll mot någon som har behandlat dig illa.',
      'Genom att behandla alla med respekt, oavsett deras bakgrund eller övertygelser',
    ],
    leadership: [
      'Genom att inspirera och motivera andra mot framgång',
      'Genom att leda med föredöme med integritet och syfte',
      'Genom att kommunicera effektivt för att vägleda och styra',
      'Genom att stärka och delegera med förtroende och respekt',
      'Genom att anpassa sig till förändringar och ta risker för tillväxt',
      'Genom att sätta en tydlig vision och riktning för teamet',
      'Genom att ge vägledning och stöd för att hjälpa andra att lyckas',
      'Genom att skapa en positiv och inkluderande teamkultur',
      'Genom att uppmuntra kreativitet och innovation bland teammedlemmar',
      'Genom att känna igen och utnyttja de unika styrkorna hos teammedlemmar',
    ],
    love: [
      'Genom att visa ömhet gentemot andra',
      'Genom att ge emotionellt stöd och omsorg',
      'Genom att sätta andras behov före sina egna',
      'Genom att uttrycka kärlek genom ord och handlingar',
      'Genom att sprida värme och vänlighet gentemot andra',
      'Genom att vårda relationerna i ens liv',
      'Genom att uttrycka kärlek genom handlingar av vänlighet',
      'Genom att vara ett stöd och tröst för nära och kära',
      'Genom att göra tid för nära och kära trots en hektisk schema',
      'Genom att känna igen vikten av kärlek i ens liv',
      'Genom att vara kärleksfull och kär mot dem som står dig nära',
      'Genom att göra uppoffringar för dem du älskar',
      'Genom att vara lojal och engagerad för dem du håller kära',
      'Genom att fira prestationer och framgångar hos nära och kära',
      'Genom att förlåta dem du älskar med ett öppet hjärta',
    ],
    'love-of-beauty': [
      'Genom att beundra vackra saker och platser',
      'Genom att skapa konst som inspirerar och fångar',
      'Genom att uppskatta elegansen i enkelhet',
      'Genom att finna glädje i estetiken i livet',
      'Genom att se skönhet i detaljerna',
      'Genom att finna glädje i estetiken av mode',
      'Genom att uppskatta skönheten i arkitektur och design',
      'Genom att beundra naturens skönhet',
      'Genom att skapa vackra och funktionella utrymmen',
      'Genom att se skönhet i harmonin av färger och former',
    ],
    'love-of-learning': [
      'Genom att ivrigt söka ny kunskap',
      'Genom att ständigt lära sig och växa',
      'Genom att omfamna möjligheter för utbildning',
      'Genom att passionerat sträva efter intellektuell tillväxt',
      'Genom att outtröttligt utöka sin förståelse',
      'Genom att kontinuerligt söka nya utmaningar och möjligheter för tillväxt',
      'Genom att omfatta misslyckanden och misstag som möjligheter att lära',
      'Genom att eftersträva utbildning och personlig utveckling med entusiasm',
      'Genom att ständigt söka nya perspektiv och idéer',
      'Genom att uppmuntra andra att eftersträva sin egen kärlek till lärande',
    ],
    modesty: [
      'Genom att erkänna andras bidrag',
      'Genom att undvika uppmärksamhetssökande beteende',
      'Genom att vara ödmjuk i sina prestationer',
      'Genom att föredra att hålla sig borta från rampljuset',
      'Genom att visa uppskattning för andras arbete',
      'Genom att erkänna andras insatser',
      'Genom att föredra att arbeta bakom kulisserna',
      'Genom att undvika självfrämjande',
      'Genom att ge kredit där kredit är berättigad',
      'Genom att fokusera på teamets framgång snarare än personligt erkännande',
    ],
    perseverance: [
      'Genom att aldrig ge upp',
      'Genom att hålla sig fokuserad och beslutsam för att övervinna utmaningar',
      'Genom att ha motståndskraft och uthållighet',
      'Genom att sträva efter framgång trots utmaningar',
      'Genom att driva framåt genom svårigheter',
      'Genom att fortsätta arbeta mot ett mål även när framsteg är långsamt',
      'Genom att vägra ge upp en uppgift, oavsett hur svår den kan tyckas vara',
      'Genom att övervinna utmaningar och motgångar med motståndskraft och beslutsamhet',
      'Genom att vara villig att lägga in extra ansträngning som krävs för att uppnå framgångar',
      'Genom att behålla fokus och beslutsamhet trots distraktioner eller hinder',
    ],
    perspective: [
      'Genom att söka flera synpunkter innan man fattar ett beslut',
      'Genom att se situationer från olika vinklar',
      'Genom att känna igen helhetsbilden',
      'Genom att förstå olika perspektiv',
      'Genom att utmana antaganden genom kritiskt tänkande',
      'Genom att erkänna begränsningarna i ens egen kunskap och förståelse',
      'Genom att överväga långsiktiga konsekvenser av beslut och handlingar',
      'Genom att förstå sambanden mellan allting',
      'Genom att erkänna och respektera mångfalden av mänskliga erfarenheter',
      'Genom att närma sig situationer med öppet sinne och en vilja att lära sig',
      'Genom att erkänna ens egna fördomar och begränsningar i tänkandet',
      'Genom att vara beredd att ifrågasätta ens egna övertygelser och antaganden',
      'Genom att söka efter olika perspektiv och erfarenheter för att bredda ens förståelse',
      'Genom att kontinuerligt utöka ens kunskap och världsbild genom lärande och utforskande',
      'Genom att erkänna komplexiteten i sociala och globala frågor och vara villig att engagera sig i dem',
    ],
    'self-regulation': [
      'Genom att kontrollera känslor',
      'Genom att bibehålla fokus',
      'Genom att skjuta upp kortsiktiga belöningar',
      'Genom att hantera stress och ångest',
      'Genom att uppvisa självkontroll',
      'Genom att hantera impulser',
      'Genom att bibehålla känslomässig balans',
      'Genom att vara medveten och närvarande i stunden',
      'Genom att praktisera självvård för att hantera känslor',
      'Genom att utveckla hanteringsmetoder för att hantera svåra situationer',
      'Genom att göra val för fysiskt och psykiskt välbefinnande',
      'Genom att sätta gränser och hantera tiden effektivt',
      'Genom att vara ansvarig för handlingar och beslut',
      'Genom att kontinuerligt lära sig och praktisera självförbättring',
      'Genom att omfatta förändringar och anpassa sig till nya situationer',
    ],
    'social-intelligence': [
      'Genom att visa känslighet för andras känslor',
      'Genom att navigera komplexa sociala situationer med lätthet',
      'Genom att läsa mellan raderna i samtal',
      'Genom att bygga starka relationer genom effektiv kommunikation',
      'Genom att känna igen och reagera lämpligt på sociala signaler',
      'Genom att visa empati och förståelse för andras perspektiv och erfarenheter',
      'Genom att vara medveten om och anpassa sig till sociala normer och förväntningar i olika miljöer',
      'Genom att navigera komplexa sociala dynamiker med takt och diplomati',
      'Genom att utveckla positiva relationer med andra genom att kommunicera effektivt och lyssna aktivt.',
      'Genom att lösa konflikter och missförstånd på ett konstruktivt och respektfullt sätt',
    ],
    spirituality: [
      'Genom att koppla samman med något större än sig själva',
      'Genom att söka inre frid genom meditation',
      'Genom att omfamna andliga praktiker för tillväxt',
      'Genom att vårda en djup känsla av syfte',
      'Genom att finna mening i livets mysterier',
      'Genom att omfatta tacksamhet som en form av andlig praktik',
      'Genom att sträva efter att leva ett liv i linje med ens värderingar och övertygelser',
      'Genom att koppla samman med naturen som en källa till andlig förnyelse',
      'Genom att utforska olika andliga traditioner och övertygelser',
      'Genom att integrera andliga praktiker i vardagen för större mening och syfte',
    ],
    teamwork: [
      'Genom effektivt samarbete med andra.',
      'Genom att värdera och respektera teammedlemmar.',
      'Genom att proaktivt stödja teamets mål.',
      'Genom att villigt dela kunskap och resurser.',
      'Genom att bygga positiva relationer med teammedlemmar.',
      'Genom att vara villig att kompromissa för att uppnå gemensamma mål',
      'Genom att kommunicera öppet och ärligt med teammedlemmar',
      'Genom att bidra till en positiv teamdynamik',
      'Genom att hålla sig själv ansvarig för sin roll i teamets framgång',
      'Genom att visa flexibilitet och anpassningsförmåga i föränderliga omständigheter',
      'Genom att vara respektfull för teammedlemmars åsikter och idéer',
      'Genom att vara villig att ta på sig olika roller och ansvarsområden vid behov',
      'Genom att fira och erkänna teammedlemmars bidrag och framgångar',
      'Genom att vara konstruktiv och stöttande vid feedback till teammedlemmar',
      'Genom att visa engagemang för teamets mål och framgång',
    ],
  },
  'en-US': {
    carefulness: [
      'By taking precautions to avoid mistakes',
      'By paying close attention to detail',
      'By thinking ahead to prevent errors',
      'By paying great attention to detail while working',
      'By double-checking my actions for accuracy',
      'By taking precautions to avoid mistakes',
      'By continuously striving to improve my work',
      'By being mindful of potential risks or hazards',
      'By anticipating and planning for potential challenges',
      'By being diligent while working to ensure quality',
      'By being careful while communicating to avoid misunderstandings',
    ],
    compassion: [
      'By showing empathy towards others',
      'By caring deeply for those in need',
      'By acting with kindness and empathy',
      "By being attentive to others' feelings",
      'By having a heart full of compassion',
      'By being patient and understanding towards others',
      'By being non-judgmental and accepting of others',
      'By offering emotional support and comfort to those in need',
      'By being generous and giving towards others',
      'By advocating for the welfare of others',
    ],
    courage: [
      'By daring in the face of adversity',
      'By being fearless in pursuit of goals',
      'By being willing to take on challenges',
      'By being confident in ones abilities',
      'By stading up for themselves and others',
      'By facing fears head-on with bravery',
      'By taking calculated risks to achieve success',
      'By standing up for what is right, even in the face of opposition',
      "By advocating for change and progress, even when it's difficult",
      'By being willing to step outside of the comfort zone',
    ],
    creativity: [
      'By brainstorming innovative ideas',
      'By inspiring with imaginative solutions',
      'By experimenting with new approaches',
      'By embracing unconventional thinking',
      'By creating art that captivates',
      'By challenging the status quo with creativity',
      'By finding beauty in the unexpected',
      'By crafting unique and original designs',
      'By pushing boundaries with imaginative flair',
      'By encouraging others to pursue creativity',
    ],
    curiosity: [
      'By always seeking to learn more',
      'By being intrigued and having a curious mindset',
      'By being open to new ideas and experiences',
      'By embracing the unknown with enthusiasm',
      'By constantly exploring the world around',
      'By constantly asking questions to gain a deeper understanding',
      'By seeking out new experiences and knowledge to satisfy curiosity',
      'By challenging assumptions and exploring alternative perspectives',
      'By continuously expanding their horizons through learning and exploration',
      'By being open-minded and receptive to new ideas and information',
    ],
    enthusiasm: [
      'By approaching challenges with enthusiastic determination',
      'By inspiring others with infectious enthusiasm',
      'By embracing new ideas with enthusiastic curiosity',
      'By sharing enthusiasm for a common goal',
      'By spreading positivity through enthusiastic energy',
      'By approaching challenges with a positive attitude and enthusiasm',
      'By inspiring others with contagious enthusiasm and energy',
      'By being passionate about work and life',
      'By spreading positivity and optimism wherever they go',
      'By being a source of positive energy and motivation for others',
    ],
    fairness: [
      'By promoting justice and equality for all',
      'By treating others with fairness and equity',
      'By seeking to understand different viewpoints',
      'By respecting diversity and inclusivity',
      'By empowering others through fair treatment',
      'By advocating for equal treatment of all individuals',
      'By challenging bias and discrimination in all forms',
      'By striving to create a level playing field for everyone',
      'By promoting diversity and inclusion in all environments',
      'By standing up for the rights of marginalized groups',
      'By recognizing and addressing systemic inequalities',
      'By supporting policies and initiatives that promote fairness and equality',
      'By making sure that choices are made based on skills and abilities, not personal likes or dislikes.',
      'By being open-minded to alternative perspectives and opinions',
      'By treating everyone with respect, regardless of who they are or where they come from.',
    ],
    forgiveness: [
      "By accepting others' apologies without hesitation",
      'By letting go of past grievances with grace',
      'By granting second chances with an open heart',
      'By moving forward with compassion and understanding',
      'By embracing forgiveness as a path to growth',
      'By letting go of resentment towards others',
      'By seeing mistakes as opportunities to learn and grow',
      'By recognizing that forgiveness is a choice',
      'By offering forgiveness as a gift to oneself and others',
      'By recognizing the humanity in others and the capacity for change',
    ],
    gratitude: [
      'By appreciating the little things in life',
      'By giving thanks for every opportunity',
      'By expressing gratitude towards others',
      'By nurturing a thankful mindset every day',
      'By seeing the good in all situations',
      'By finding joy in the simple things in life',
      'By recognizing the good in every situation',
      'By being thankful for the people in their life',
      'By developing a positive and thankful mindset',
      'By expressing appreciation for the blessings in life',
      'By being grateful for the given opportunities',
      'By seeing challenges as opportunities to learn and grow',
      'By recognizing the value of hard work and perseverance',
      'By giving back to others as an expression of gratitude',
      'By practicing gratitude as a form of self-care and mindfulness',
    ],
    grit: [
      'By persevering through challenges with determination',
      'By overcoming challenges with determination.',
      'By continuously striving for progress despite setbacks',
      'By maintaining focus and determination in the face of adversity',
      'By persistently pursuing goals with relentless grit',
      'By embracing challenges as opportunities for growth',
      'By refusing to give up in the face of adversity',
      'By pushing through discomfort to achieve goals',
      'By maintaining focus and determination over long periods of time',
      'By being resilient and persistent in pursuit of success',
    ],
    honesty: [
      'By speaking truthfully in all situations',
      'By admitting mistakes and taking responsibility',
      'By being transparent and authentic',
      'By respecting the importance of honesty',
      'By striving for integrity in all actions',
      "By being truthful even when it's difficult",
      "By taking responsibility for one's actions and mistakes",
      "By being honest with oneself about one's strengths and weaknesses",
      'By refraining from lying or bending the truth to avoid negative consequences',
      'By being transparent and straightforward in communication',
    ],
    hope: [
      'By maintaining hope in difficult situations',
      'By seeking out hope in dark times',
      'By nurturing hope in oneself and others',
      'By choosing hope over despair',
      'By inspiring others with hopeful words and actions',
      'By believing in a better future',
      'By finding inspiration in the face of adversity',
      "By trusting in one's ability to overcome challenges",
      'By holding onto optimism in difficult times',
      'By inspiring hope in others through words and actions',
      'By continuing to pursue goals despite obstacles',
      'By seeing setbacks as temporary and opportunities for growth',
      'By cultivating resilience and perseverance through hope',
      'By finding strength in hope and positivity',
      'By believing that things will eventually work out for the best',
    ],
    humour: [
      'By being quick-witted and playful',
      "By bringing a smile to others' faces",
      'By finding joy in laughter and fun',
      'By not taking things too seriously',
      'By lightening the mood and easing tension',
      'By finding the funny side of difficult situations',
      'By using humor to diffuse tension and conflict',
      'By spreading joy through laughter and playfulness',
      'By being playful and lighthearted in interactions with others',
      'By making others laugh with clever and witty remarks',
      'By finding humor in everyday situations',
      'By being able to laugh at oneself and not take oneself too seriously',
      'By using humor as a coping mechanism in difficult times',
      'By being a source of humor and joy for others',
      'By making the world a brighter place through humor and playfulness',
    ],
    judgement: [
      'By making sound and fair decisions based on reason and evidence',
      'By evaluating situations carefully before making a decision',
      'By weighing the pros and cons before making a choice',
      'By considering different perspectives before forming an opinion',
      'By being able to make difficult decisions when necessary',
      "By taking responsibility for one's actions and decisions",
      'By being able to see the big picture while also paying attention to details',
      'By using good judgement to navigate complex situations',
      "By recognizing one's own biases and being open to new information",
      'By balancing reason and intuition to make wise decisions',
    ],
    kindness: [
      'By being nice to other people',
      'By helping others in need',
      'By being kind and understanding towards others',
      'By actively listening and understanding others',
      "By being considerate and thoughtful of others' feelings",
      'By being there for someone in their time of need',
      "By offering a kind word or gesture to brighten someone's day",
      "By helping someone even when it's not easy or convenient.",
      'By being kind to someone who has wronged you.',
      'By treating everyone with respect, regardless of their background or beliefs',
    ],
    leadership: [
      'By inspiring and motivating others towards success',
      'By leading by example with integrity and purpose',
      'By communicating effectively to guide and direct',
      'By empowering and delegating with trust and respect',
      'By adapting to change and taking risks for growth',
      'By setting a clear vision and direction for the team',
      'By providing guidance and support to help others succeed',
      'By creating a positive and inclusive team culture',
      'By encouraging creativity and innovation among team members',
      'By recognizing and utilizing the unique strengths of team members',
    ],
    love: [
      'By showing affection towards others',
      'By providing emotional support and care',
      "By putting others' needs before their own",
      'By expressing love through words and actions',
      'By radiating warmth and kindness towards others',
      "By cherishing the relationships in one's life",
      'By expressing love through acts of kindness',
      'By being a source of support and comfort for loved ones',
      'By making time for loved ones despite a busy schedule',
      "By recognizing the importance of love in one's life",
      'By being affectionate and loving towards those close to you',
      'By making sacrifices for the ones you love',
      'By being loyal and committed to those you hold dear',
      'By celebrating the achievements and successes of loved ones',
      'By forgiving those you love with an open heart',
    ],
    'love-of-beauty': [
      'By admiring beautiful things and places',
      'By creating art that inspires and captivates',
      'By appreciating the elegance in simplicity',
      'By finding joy in the aesthetics of life',
      'By seeing beauty in the details',
      'By finding joy in the aesthetics of fashion',
      'By appreciating the beauty of architecture and design',
      'By admiring the beauty of the natural world',
      'By creating beautiful and functional spaces',
      'By seeing beauty in the harmony of colors and shapes',
    ],
    'love-of-learning': [
      'By eagerly seeking new knowledge',
      'By constantly learning and growing',
      'By embracing opportunities for education',
      'By passionately pursuing intellectual growth',
      'By relentlessly expanding their understanding',
      'By continuously seeking out new challenges and opportunities for growth',
      'By embracing failures and mistakes as opportunities to learn',
      'By pursuing education and personal development with enthusiasm',
      'By constantly seeking new perspectives and ideas',
      'By encouraging others to pursue their own love of learning',
    ],
    modesty: [
      "By acknowledging others' contributions",
      'By avoiding attention-seeking behavior',
      'By being humble in their accomplishments',
      'By preferring to stay out of the spotlight',
      "By showing appreciation for others' work",
      'By recognizing the contributions of others',
      'By preferring to work behind the scenes',
      'By avoiding self-promotion',
      'By giving credit where credit is due',
      "By focusing on the team's success rather than personal recognition",
    ],
    perseverance: [
      'By never giving up',
      'By staying focused and determined to overcome challenges',
      'By having resilience and persistence',
      'By striving for success despite challenges',
      'By pushing forward through difficulties',
      'By continuing to work towards a goal even when progress is slow',
      'By refusing to give up on a task, no matter how difficult it may seem',
      'By overcoming challenges and setbacks with resilience and determination',
      'By being willing to put in extra effort required to achieve successes',
      'By maintaining focus and determination despite distractions or obstacles',
    ],
    perspective: [
      'By seeking multiple viewpoints before making a decision',
      'By viewing situations from various angles',
      'By recognizing the big picture',
      'By understanding diverse perspectives',
      'By challenging assumptions through critical thinking',
      "By recognizing the limitations of one's own knowledge and understanding",
      'By considering the long-term implications of decisions and actions',
      'By understanding the interconnectedness of all things',
      'By acknowledging and respecting the diversity of human experience',
      'By approaching situations with an open mind and a willingness to learn',
      "By recognizing one's own biases and limitations in thinking",
      "By being willing to challenge one's own beliefs and assumptions",
      "By seeking out diverse perspectives and experiences to broaden one's understanding",
      "By continuously expanding one's knowledge and worldview through learning and exploration",
      'By recognizing the complexity of social and global issues and being willing to engage with them',
    ],
    'self-regulation': [
      'By controlling emotions',
      'By maintaining focus',
      'By delaying short-term rewards',
      'By managing stress and anxiety',
      'By exhibiting self-control',
      'By managing impulses',
      'By maintaining emotional balance',
      'By being mindful and present in the moment',
      'By practicing self-care to manage emotions',
      'By developing coping methods to manage difficult situations',
      'By making choices for physical and mental well-being',
      'By setting boundaries and managing time effectively',
      'By being accountable for actions and decisions',
      'By continuously learning and practicing self-improvement',
      'By embracing change and adapting to new situations',
    ],
    'social-intelligence': [
      "By demonstrating sensitivity to others' feelings",
      'By navigating complex social situations with ease',
      'By reading between the lines in conversations',
      'By building strong relationships through effective communication',
      'By recognizing and responding appropriately to social cues',
      "By demonstrating empathy and understanding towards others' perspectives and experiences",
      'By being aware of and adapting to social norms and expectations in various settings',
      'By navigating complex social dynamics with tact and diplomacy',
      'By developing positive relationships with others by communicating effectively and listening actively.',
      'By resolving conflicts and misunderstandings in a constructive and respectful manner',
    ],
    spirituality: [
      'By connecting with something greater than themselves',
      'By seeking inner peace through meditation',
      'By embracing spiritual practices for growth',
      'By nurturing a deep sense of purpose',
      'By finding meaning in the mysteries of life',
      'By embracing gratitude as a form of spiritual practice',
      "By seeking to live a life aligned with one's values and beliefs",
      'By connecting with nature as a source of spiritual renewal',
      'By exploring different spiritual traditions and beliefs',
      'By integrating spiritual practices into daily life for greater meaning and purpose',
    ],
    teamwork: [
      'By effective collaboration with others.',
      'By valuing and respecting team members.',
      'By proactively supporting team goals.',
      'By willingly sharing knowledge and resources.',
      'By building positive relationships with team members.',
      'By being willing to compromise to achieve shared goals',
      'By communicating openly and honestly with team members',
      'By contributing to a positive team dynamic',
      "By holding oneself accountable for their role in the team's success",
      'By demonstrating flexibility and adaptability in changing circumstances',
      "By being respectful of team members' opinions and ideas",
      'By being willing to take on different roles and responsibilities as needed',
      "By celebrating and recognizing team members' contributions and successes",
      'By being constructive and supportive in providing feedback to team members',
      "By demonstrating a commitment to the team's goals and success",
    ],
  },
};
