const countries = [
  {code: 'afg', name: 'Afghanistan'},
  {code: 'ala', name: 'Åland Islands'},
  {code: 'alb', name: 'Albania'},
  {code: 'dza', name: 'Algeria'},
  {code: 'asm', name: 'American Samoa'},
  {code: 'and', name: 'Andorra'},
  {code: 'ago', name: 'Angola'},
  {code: 'aia', name: 'Anguilla'},
  {code: 'ata', name: 'Antarctica'},
  {code: 'atg', name: 'Antigua and Barbuda'},
  {code: 'arg', name: 'Argentina'},
  {code: 'arm', name: 'Armenia'},
  {code: 'abw', name: 'Aruba'},
  {code: 'aus', name: 'Australia'},
  {code: 'aut', name: 'Austria'},
  {code: 'aze', name: 'Azerbaijan'},
  {code: 'bhs', name: 'Bahamas'},
  {code: 'bhr', name: 'Bahrain'},
  {code: 'bgd', name: 'Bangladesh'},
  {code: 'brb', name: 'Barbados'},
  {code: 'blr', name: 'Belarus'},
  {code: 'bel', name: 'Belgium'},
  {code: 'blz', name: 'Belize'},
  {code: 'ben', name: 'Benin'},
  {code: 'bmu', name: 'Bermuda'},
  {code: 'btn', name: 'Bhutan'},
  {code: 'bol', name: 'Bolivia'},
  {code: 'bih', name: 'Bosnia and Herzegovina'},
  {code: 'bwa', name: 'Botswana'},
  {code: 'bvt', name: 'Bouvet Island'},
  {code: 'bra', name: 'Brazil'},
  {code: 'iot', name: 'British Indian Ocean Territory'},
  {code: 'vgb', name: 'British Virgin Islands'},
  {code: 'brn', name: 'Brunei'},
  {code: 'bgr', name: 'Bulgaria'},
  {code: 'bfa', name: 'Burkina Faso'},
  {code: 'bdi', name: 'Burundi'},
  {code: 'khm', name: 'Cambodia'},
  {code: 'cmr', name: 'Cameroon'},
  {code: 'can', name: 'Canada'},
  {code: 'cpv', name: 'Cape Verde'},
  {code: 'bes', name: 'Caribbean Netherlands'},
  {code: 'cym', name: 'Cayman Islands'},
  {code: 'caf', name: 'Central African Republic'},
  {code: 'tcd', name: 'Chad'},
  {code: 'chl', name: 'Chile'},
  {code: 'chn', name: 'China'},
  {code: 'cxr', name: 'Christmas Island'},
  {code: 'cck', name: 'Cocos (Keeling) Islands'},
  {code: 'col', name: 'Colombia'},
  {code: 'com', name: 'Comoros'},
  {code: 'cok', name: 'Cook Islands'},
  {code: 'cri', name: 'Costa Rica'},
  {code: 'hrv', name: 'Croatia'},
  {code: 'cub', name: 'Cuba'},
  {code: 'cuw', name: 'Curaçao'},
  {code: 'cyp', name: 'Cyprus'},
  {code: 'cze', name: 'Czechia'},
  {code: 'dnk', name: 'Denmark'},
  {code: 'dji', name: 'Djibouti'},
  {code: 'dma', name: 'Dominica'},
  {code: 'dom', name: 'Dominican Republic'},
  {code: 'cod', name: 'DR Congo'},
  {code: 'ecu', name: 'Ecuador'},
  {code: 'egy', name: 'Egypt'},
  {code: 'slv', name: 'El Salvador'},
  {code: 'gnq', name: 'Equatorial Guinea'},
  {code: 'eri', name: 'Eritrea'},
  {code: 'est', name: 'Estonia'},
  {code: 'swz', name: 'Eswatini'},
  {code: 'eth', name: 'Ethiopia'},
  {code: 'flk', name: 'Falkland Islands'},
  {code: 'fro', name: 'Faroe Islands'},
  {code: 'fji', name: 'Fiji'},
  {code: 'fin', name: 'Finland'},
  {code: 'fra', name: 'France'},
  {code: 'guf', name: 'French Guiana'},
  {code: 'pyf', name: 'French Polynesia'},
  {code: 'atf', name: 'French Southern and Antarctic Lands'},
  {code: 'gab', name: 'Gabon'},
  {code: 'gmb', name: 'Gambia'},
  {code: 'geo', name: 'Georgia'},
  {code: 'deu', name: 'Germany'},
  {code: 'gha', name: 'Ghana'},
  {code: 'gib', name: 'Gibraltar'},
  {code: 'grc', name: 'Greece'},
  {code: 'grl', name: 'Greenland'},
  {code: 'grd', name: 'Grenada'},
  {code: 'glp', name: 'Guadeloupe'},
  {code: 'gum', name: 'Guam'},
  {code: 'gtm', name: 'Guatemala'},
  {code: 'ggy', name: 'Guernsey'},
  {code: 'gin', name: 'Guinea'},
  {code: 'gnb', name: 'Guinea-Bissau'},
  {code: 'guy', name: 'Guyana'},
  {code: 'hti', name: 'Haiti'},
  {code: 'hmd', name: 'Heard Island and McDonald Islands'},
  {code: 'hnd', name: 'Honduras'},
  {code: 'hkg', name: 'Hong Kong'},
  {code: 'hun', name: 'Hungary'},
  {code: 'isl', name: 'Iceland'},
  {code: 'ind', name: 'India'},
  {code: 'idn', name: 'Indonesia'},
  {code: 'irn', name: 'Iran'},
  {code: 'irq', name: 'Iraq'},
  {code: 'irl', name: 'Ireland'},
  {code: 'imn', name: 'Isle of Man'},
  {code: 'isr', name: 'Israel'},
  {code: 'ita', name: 'Italy'},
  {code: 'civ', name: 'Ivory Coast'},
  {code: 'jam', name: 'Jamaica'},
  {code: 'jpn', name: 'Japan'},
  {code: 'jey', name: 'Jersey'},
  {code: 'jor', name: 'Jordan'},
  {code: 'kaz', name: 'Kazakhstan'},
  {code: 'ken', name: 'Kenya'},
  {code: 'kir', name: 'Kiribati'},
  {code: 'unk', name: 'Kosovo'},
  {code: 'kwt', name: 'Kuwait'},
  {code: 'kgz', name: 'Kyrgyzstan'},
  {code: 'lao', name: 'Laos'},
  {code: 'lva', name: 'Latvia'},
  {code: 'lbn', name: 'Lebanon'},
  {code: 'lso', name: 'Lesotho'},
  {code: 'lbr', name: 'Liberia'},
  {code: 'lby', name: 'Libya'},
  {code: 'lie', name: 'Liechtenstein'},
  {code: 'ltu', name: 'Lithuania'},
  {code: 'lux', name: 'Luxembourg'},
  {code: 'mac', name: 'Macau'},
  {code: 'mdg', name: 'Madagascar'},
  {code: 'mwi', name: 'Malawi'},
  {code: 'mys', name: 'Malaysia'},
  {code: 'mdv', name: 'Maldives'},
  {code: 'mli', name: 'Mali'},
  {code: 'mlt', name: 'Malta'},
  {code: 'mhl', name: 'Marshall Islands'},
  {code: 'mtq', name: 'Martinique'},
  {code: 'mrt', name: 'Mauritania'},
  {code: 'mus', name: 'Mauritius'},
  {code: 'myt', name: 'Mayotte'},
  {code: 'mex', name: 'Mexico'},
  {code: 'fsm', name: 'Micronesia'},
  {code: 'mda', name: 'Moldova'},
  {code: 'mco', name: 'Monaco'},
  {code: 'mng', name: 'Mongolia'},
  {code: 'mne', name: 'Montenegro'},
  {code: 'msr', name: 'Montserrat'},
  {code: 'mar', name: 'Morocco'},
  {code: 'moz', name: 'Mozambique'},
  {code: 'mmr', name: 'Myanmar'},
  {code: 'nam', name: 'Namibia'},
  {code: 'nru', name: 'Nauru'},
  {code: 'npl', name: 'Nepal'},
  {code: 'nld', name: 'Netherlands'},
  {code: 'ncl', name: 'New Caledonia'},
  {code: 'nzl', name: 'New Zealand'},
  {code: 'nic', name: 'Nicaragua'},
  {code: 'ner', name: 'Niger'},
  {code: 'nga', name: 'Nigeria'},
  {code: 'niu', name: 'Niue'},
  {code: 'nfk', name: 'Norfolk Island'},
  {code: 'prk', name: 'North Korea'},
  {code: 'mkd', name: 'North Macedonia'},
  {code: 'mnp', name: 'Northern Mariana Islands'},
  {code: 'nor', name: 'Norway'},
  {code: 'omn', name: 'Oman'},
  {code: 'pak', name: 'Pakistan'},
  {code: 'plw', name: 'Palau'},
  {code: 'pse', name: 'Palestine'},
  {code: 'pan', name: 'Panama'},
  {code: 'png', name: 'Papua New Guinea'},
  {code: 'pry', name: 'Paraguay'},
  {code: 'per', name: 'Peru'},
  {code: 'phl', name: 'Philippines'},
  {code: 'pcn', name: 'Pitcairn Islands'},
  {code: 'pol', name: 'Poland'},
  {code: 'prt', name: 'Portugal'},
  {code: 'pri', name: 'Puerto Rico'},
  {code: 'qat', name: 'Qatar'},
  {code: 'cog', name: 'Republic of the Congo'},
  {code: 'reu', name: 'Réunion'},
  {code: 'rou', name: 'Romania'},
  {code: 'rus', name: 'Russia'},
  {code: 'rwa', name: 'Rwanda'},
  {code: 'blm', name: 'Saint Barthélemy'},
  {code: 'shn', name: 'Saint Helena, Ascension and Tristan da Cunha'},
  {code: 'kna', name: 'Saint Kitts and Nevis'},
  {code: 'lca', name: 'Saint Lucia'},
  {code: 'maf', name: 'Saint Martin'},
  {code: 'spm', name: 'Saint Pierre and Miquelon'},
  {code: 'vct', name: 'Saint Vincent and the Grenadines'},
  {code: 'wsm', name: 'Samoa'},
  {code: 'smr', name: 'San Marino'},
  {code: 'stp', name: 'São Tomé and Príncipe'},
  {code: 'sau', name: 'Saudi Arabia'},
  {code: 'sen', name: 'Senegal'},
  {code: 'srb', name: 'Serbia'},
  {code: 'syc', name: 'Seychelles'},
  {code: 'sle', name: 'Sierra Leone'},
  {code: 'sgp', name: 'Singapore'},
  {code: 'sxm', name: 'Sint Maarten'},
  {code: 'svk', name: 'Slovakia'},
  {code: 'svn', name: 'Slovenia'},
  {code: 'slb', name: 'Solomon Islands'},
  {code: 'som', name: 'Somalia'},
  {code: 'zaf', name: 'South Africa'},
  {code: 'sgs', name: 'South Georgia'},
  {code: 'kor', name: 'South Korea'},
  {code: 'ssd', name: 'South Sudan'},
  {code: 'esp', name: 'Spain'},
  {code: 'lka', name: 'Sri Lanka'},
  {code: 'sdn', name: 'Sudan'},
  {code: 'sur', name: 'Suriname'},
  {code: 'sjm', name: 'Svalbard and Jan Mayen'},
  {code: 'swe', name: 'Sweden'},
  {code: 'che', name: 'Switzerland'},
  {code: 'syr', name: 'Syria'},
  {code: 'twn', name: 'Taiwan'},
  {code: 'tjk', name: 'Tajikistan'},
  {code: 'tza', name: 'Tanzania'},
  {code: 'tha', name: 'Thailand'},
  {code: 'tls', name: 'Timor-Leste'},
  {code: 'tgo', name: 'Togo'},
  {code: 'tkl', name: 'Tokelau'},
  {code: 'ton', name: 'Tonga'},
  {code: 'tto', name: 'Trinidad and Tobago'},
  {code: 'tun', name: 'Tunisia'},
  {code: 'tur', name: 'Turkey'},
  {code: 'tkm', name: 'Turkmenistan'},
  {code: 'tca', name: 'Turks and Caicos Islands'},
  {code: 'tuv', name: 'Tuvalu'},
  {code: 'uga', name: 'Uganda'},
  {code: 'ukr', name: 'Ukraine'},
  {code: 'are', name: 'United Arab Emirates'},
  {code: 'gbr', name: 'United Kingdom'},
  {code: 'usa', name: 'United States'},
  {code: 'umi', name: 'United States Minor Outlying Islands'},
  {code: 'vir', name: 'United States Virgin Islands'},
  {code: 'ury', name: 'Uruguay'},
  {code: 'uzb', name: 'Uzbekistan'},
  {code: 'vut', name: 'Vanuatu'},
  {code: 'vat', name: 'Vatican City'},
  {code: 'ven', name: 'Venezuela'},
  {code: 'vnm', name: 'Vietnam'},
  {code: 'wlf', name: 'Wallis and Futuna'},
  {code: 'esh', name: 'Western Sahara'},
  {code: 'yem', name: 'Yemen'},
  {code: 'zmb', name: 'Zambia'},
  {code: 'zwe', name: 'Zimbabwe'},
];

export default countries;
