export const Article = {
  type: 'object',
  properties: {
    id: {type: 'string'},
    translations: {
      type: 'array',
      items: {$ref: '#/definitions/ArticleTranslation'},
    },
    thumbnail: {type: 'string'},
    length: {type: 'string'},
    strengths: {type: 'array', items: {$ref: '#/definitions/StrengthSlug'}},
    category: {type: 'string'},
    order: {type: 'number'},
    updatedAt: {type: 'string'},
    createdAt: {type: 'string'},
    updatedBy: {$ref: '#/definitions/UserInfo'},
    categoryPath: {
      type: 'array',
      items: {
        type: 'object',
        properties: {
          id: {type: 'string'},
          translations: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                language: {$ref: '#/definitions/LanguageCode'},
                name: {type: 'string'},
              },
              required: ['language', 'name'],
            },
          },
        },
        required: ['id', 'translations'],
      },
    },
    isHidden: {type: 'boolean'},
    isLocked: {type: 'boolean'},
    isTimelineArticle: {type: 'boolean'},
    timelineChapter: {$ref: '#/definitions/ArticleChapter'},
    timelineAgeGroup: {$ref: '#/definitions/AgeGroup'},
    timelineStrength: {$ref: '#/definitions/StrengthSlug'},
  },
  required: [
    'id',
    'translations',
    'thumbnail',
    'length',
    'strengths',
    'category',
    'order',
    'updatedAt',
    'createdAt',
    'updatedBy',
    'categoryPath',
    'isHidden',
    'isLocked',
    'isTimelineArticle',
    'timelineChapter',
    'timelineAgeGroup',
    'timelineStrength',
  ],
} as const;
