export const StrengthSlug = {
  type: 'string',
  enum: [
    'carefulness',
    'compassion',
    'courage',
    'creativity',
    'curiosity',
    'enthusiasm',
    'fairness',
    'forgiveness',
    'gratitude',
    'grit',
    'honesty',
    'hope',
    'humour',
    'judgement',
    'kindness',
    'leadership',
    'love',
    'loveOfBeauty',
    'loveOfLearning',
    'modesty',
    'perseverance',
    'perspective',
    'selfRegulation',
    'socialIntelligence',
    'spirituality',
    'teamwork',
  ],
} as const;
